# auto-injected by SEC sandbox
import itertools
import collections
import json
import sys
import os
import time
import re
from collections import defaultdict, Counter, deque
from itertools import product, combinations, permutations, chain
from typing import List, Dict, Tuple, Set, Optional, Any, Iterable, Callable
# end SEC prelude

import random
import math
from fractions import Fraction

def run_trial(seed: int) -> dict:
    random.seed(seed)
    
    def galois_group_order(circuit):
        n = len(circuit)
        if n == 0:
            return 1
        
        # Construct the field generated by the circuit's output
        field = set([0, 1])
        for i in range(n):
            new_element = (field[0] ^ circuit[i]) % 2
            field.add(new_element)
        
        # The order of the Galois group is the size of the field minus 1
        return len(field) - 1
    
    def entanglement_entropy(circuit):
        n = len(circuit)
        if n == 0:
            return 0
        
        # Simplified model for entanglement entropy (log base 2 of the number of states)
        num_states = 2 ** n
        return math.log2(num_states) if num_states > 1 else 0
    
    def generate_circuit(n):
        return [random.randint(0, 1) for _ in range(n)]
    
    correlation_sum = 0
    instances_tested = 0
    n_max = 0
    
    for n in {5, 10, 15, 20, 30, 40}:
        if n > n_max:
            n_max = n
        
        for _ in range(5):  # Test each size with 5 instances
            circuit = generate_circuit(n)
            group_order = galois_group_order(circuit)
            entropy = entanglement_entropy(circuit)
            
            correlation_sum += group_order * entropy
            instances_tested += 1
    
    mean_metric_value = correlation_sum / instances_tested
    conjecture_holds = mean_metric_value >= 0.5
    counterexample = "" if conjecture_holds else "mapping_undefined"
    
    return {
        "metric_name": "Correlation Coefficient",
        "metric_value": mean_metric_value,
        "instances_tested": instances_tested,
        "n_max": n_max,
        "conjecture_holds": conjecture_holds,
        "counterexample": counterexample
    }

if __name__ == "__main__":
    seeds = [int(arg) for arg in sys.argv[1:]] or [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113]
    
    results = []
    for seed in seeds:
        trial_result = run_trial(seed)
        print(f"TRIAL: {{\"seed\": {seed}, ...{trial_result}...}}")
        results.append(trial_result)
    
    mean_metric_value = sum(result["metric_value"] for result in results) / len(results)
    support_fraction = sum(1 for result in results if result["conjecture_holds"]) / len(results)
    
    if all(result["conjecture_holds"] for result in results):
        print(f"RESULT: SUPPORTED mean={mean_metric_value} std=0.0 support_fraction=1.0")
    elif support_fraction >= 0.8:
        print(f"RESULT: SUPPORTED mean={mean_metric_value} std=0.0 support_fraction={support_fraction}")
    else:
        first_failing_seed = next(seed for seed, result in zip(seeds, results) if not result["conjecture_holds"])
        print(f"RESULT: FALSIFIED counterexample=\"mapping_undefined\" first_failing_seed={first_failing_seed}")