# auto-injected by SEC sandbox
import itertools
import collections
import json
import sys
import os
import time
import re
from collections import defaultdict, Counter, deque
from itertools import product, combinations, permutations, chain
from fractions import Fraction
from typing import List, Dict, Tuple, Set, Optional, Any, Iterable, Callable
# end SEC prelude

import random
import math

def run_trial(seed: int) -> dict:
    # Set seed for reproducibility
    random.seed(seed)
    
    # Define constants and parameters
    alpha = 1.0  # Example constant, adjust as needed
    
    # Generate a random communication complexity instance with varying rank variance
    n = random.randint(5, 30)  # Instance size
    rank_variance = random.uniform(0.1, 2.0)  # Random rank variance
    
    # Compute the ideal generated by the Boolean functions for this instance
    # This is a placeholder; replace with actual computation based on the problem
    ideal_rank = int(rank_variance ** 2 * alpha)
    
    # Compare the computed ranks with α times the square of the rank variance
    if ideal_rank <= alpha * rank_variance ** 2:
        conjecture_holds = True
        counterexample = ""
    else:
        conjecture_holds = False
        counterexample = "Rank variance too high for given ideal rank"
    
    return {
        "metric_name": "ideal_rank",
        "metric_value": ideal_rank,
        "instances_tested": 1,
        "n_max": n,
        "conjecture_holds": conjecture_holds,
        "counterexample": counterexample
    }

if __name__ == "__main__":
    import sys
    
    seeds = [int(arg) for arg in sys.argv[1:]] if sys.argv[1:] else [2**i + 1 for i in range(5, 8)]
    
    results = []
    for seed in seeds:
        trial_result = run_trial(seed)
        print(f"TRIAL: {trial_result}")
        results.append(trial_result)
    
    # Compute mean/std of metric_value and fraction of seeds where conjecture_holds
    if not results:
        print("RESULT: INCONCLUSIVE no trials ran")
        sys.exit(0)
    
    total_metric = sum(result["metric_value"] for result in results)
    mean_metric = total_metric / len(results)
    std_metric = math.sqrt(sum((result["metric_value"] - mean_metric) ** 2 for result in results) / len(results))
    
    support_count = sum(1 for result in results if result["conjecture_holds"])
    support_fraction = support_count / len(results)
    
    if support_fraction >= 0.8:
        print(f"RESULT: SUPPORTED mean={mean_metric} std={std_metric} support_fraction={support_fraction}")
    else:
        first_failing_seed = next(seed for seed, result in zip(seeds, results) if not result["conjecture_holds"])
        print(f"RESULT: FALSIFIED counterexample=\"Rank variance too high\" first_failing_seed={first_failing_seed}")