# auto-injected by SEC sandbox
import itertools
import collections
import json
import sys
import os
import time
import re
from collections import defaultdict, Counter, deque
from itertools import product, combinations, permutations, chain
from typing import List, Dict, Tuple, Set, Optional, Any, Iterable, Callable
# end SEC prelude

import random
import math
from fractions import Fraction

def run_trial(seed: int) -> dict:
    random.seed(seed)
    
    def galois_group_order(circuit):
        n = len(circuit)
        if n == 0:
            return 1
        
        # Construct the field generated by the circuit's output
        field = {0, 1}
        for i in range(n):
            new_element = (field[0] ^ circuit[i]) % 2
            field.add(new_element)
        
        # Find the minimal order of the Galois group
        order = 1
        while True:
            if all((x ** order) % 2 == x for x in field):
                return order
            order += 1
    
    def entanglement_entropy(circuit):
        n = len(circuit)
        # Simplified model: assume the circuit has a uniform distribution of outputs
        return -n * math.log2(1 / (2 ** n))
    
    def generate_circuit(n):
        return [random.randint(0, 1) for _ in range(n)]
    
    correlation_values = []
    instances_tested = 0
    
    for n in {5, 10, 15, 20, 30, 40}:
        for _ in range(5):
            circuit = generate_circuit(n)
            group_order = galois_group_order(circuit)
            entropy = entanglement_entropy(circuit)
            correlation_values.append((group_order, entropy))
            instances_tested += 1
    
    if not correlation_values:
        return {
            "metric_name": "correlation_coefficient",
            "metric_value": None,
            "instances_tested": 0,
            "n_max": 40,
            "conjecture_holds": False,
            "counterexample": "mapping_undefined"
        }
    
    correlation_sum = sum(x * y for x, y in correlation_values)
    correlation_mean = correlation_sum / len(correlation_values)
    correlation_std = math.sqrt(sum((x * y - correlation_mean) ** 2 for x, y in correlation_values) / len(correlation_values))
    
    return {
        "metric_name": "correlation_coefficient",
        "metric_value": correlation_mean,
        "instances_tested": instances_tested,
        "n_max": 40,
        "conjecture_holds": correlation_mean >= 0.5,
        "counterexample": ""
    }

if __name__ == "__main__":
    seeds = [int(x) for x in sys.argv[1:]] or [2, 3, 5, 7, 11, 13, 17, 19, 23, 29] * 3
    results = []
    
    for seed in seeds:
        trial_result = run_trial(seed)
        print(f"TRIAL: {{\"seed\": {seed}, ...run_trial output...}}")
        results.append(trial_result)
    
    if all("conjecture_holds" in result and result["conjecture_holds"] for result in results):
        support_fraction = sum(1 for result in results if "conjecture_holds" in result and result["conjecture_holds"]) / len(results)
        print(f"RESULT: SUPPORTED mean={sum(result['metric_value'] for result in results) / len(results)} std={math.sqrt(sum((result['metric_value'] - sum(result['metric_value'] for result in results) / len(results)) ** 2 for result in results) / len(results))} support_fraction={support_fraction}")
    elif any("conjecture_holds" in result and not result["conjecture_holds"] for result in results):
        first_failing_seed = next(seed for seed, result in zip(seeds, results) if "conjecture_holds" in result and not result["conjecture_holds"])
        print(f"RESULT: FALSIFIED counterexample=\"\" first_failing_seed={first_failing_seed}")
    else:
        print("RESULT: INCONCLUSIVE no seeds tested")