import random
import itertools
from functools import reduce
from collections import defaultdict
import sys

# We are working in characteristic 2, so everything is mod 2.
# Since Chow groups are hard to compute in general, we focus on the zero-dimensional
# variety V_φ ⊆ 𝔽₂ⁿ defined by a 3-CNF formula φ, interpreted as cubic polynomials.

# However, note: the conjecture involves CH^1(V_φ)[2], but for a zero-dimensional variety,
# the codimension-1 Chow group CH^1 would normally be trivial because there are no
# subvarieties of codimension 1 (since dim V_φ = 0). This suggests a fundamental issue.

# Let's reevaluate: if V_φ is zero-dimensional (finitely many points), then:
#   CH^0(V_φ) = Z^0(V_φ) = free abelian group on points (mod 2 here? not standard)
#   CH^1(V_φ) = 0, since no subvarieties of codimension 1 exist.

# But the conjecture refers to CH^1(V_φ)[2] for a variety V_φ ⊆ 𝔽₂ⁿ defined by 3-CNF.
# Unless V_φ is not zero-dimensional? But over algebraically closed field, yes — but we're over 𝔽₂.

# Actually, V_φ is a finite set of points in 𝔽₂ⁿ, so it's zero-dimensional.
# Therefore, CH^1(V_φ) = 0, so |CH^1(V_φ)[2]| = 1? No: the group is trivial, so |CH^1(V_φ)[2]| = 1?
# Wait: the trivial group has one element, so |CH^1(V_φ)[2]| = 1 ⇒ log₂(1+1)=1.

# But minimum resolution width of an unsatisfiable 3-CNF can be 1? No: width is number of literals in a clause.
# Minimum width in resolution refutation is at least 1, but for unsatisfiable formulas, it's at least 1.
# However, for example, {x, ¬x} has width 1. But that's 1-CNF.

# For 3-CNF, minimum clause width is 3. But resolution can derive smaller clauses.

# Actually, resolution width is the maximum number of literals in any clause in the refutation.
# Minimum such over all refutations.

# But if CH^1(V_φ)[2] is always trivial (size 1), then log₂(1+1)=1, and since resolution width ≥1 always,
# the inequality holds trivially.

# This suggests either:
#   (a) The conject is trivially true (but uninteresting), or
#   (b) There is a misinterpretation of CH^1 for zero-dim varieties, or
#   (c) V_φ is meant to be the projective closure or something else.

# But the conjecture says: "V_φ ⊆ (𝔽_2)^n", so affine variety over finite field.

# Moreover, Chow groups are usually defined for irreducible varieties or over algebraically closed fields.
# Over finite fields, and for reducible zero-dim schemes, the Chow group CH^0 is the group of 0-cycles
# modulo rational equivalence. For zero-dim schemes, rational equivalence is trivial: every 0-cycle is principal?
# Actually, no: on a zero-dim scheme, every function is constant on components, so divisors of functions are zero.

# So Z^0(V_φ) = free group on points, and principal divisors are 0 ⇒ CH^0(V_φ) = Z^0(V_φ).
# But CH^1? That would be for codimension 1 cycles — but if dim V_φ = 0, then codim 1 = -1, so no cycles.

# Hence CH^1(V_φ) = 0 always.

# Therefore |CH^1(V_φ)[2]| = 1? No: the group has one element ⇒ |G| = 1 ⇒ |G|+1 = 2 ⇒ log₂(2)=1.

# So the conjecture says: min resolution width ≥ 1, which is always true.

# But this makes the conject not falsifiable — it's trivially true.

# However, the test strategy says: "compute CH^1(V_φ)[2] as kernel of boundary map modulo principal cycles"
# — which suggests they are thinking of a complex for higher Chow groups or something else.

# Alternatively, could it be CH_0 (zero-cycles) instead of CH^1? But the conjecture says CH^1.

# Another possibility: perhaps V_φ is not the solution variety, but the "clause variety" in a larger space?
# But the conjecture says: "interpreting each clause as a degree-3 polynomial over 𝔽_2".

# Example: clause (x∨y∨¬z) becomes polynomial: (1+x)(1+y)z = 0? No — in 𝔽_2, x is 0 or 1.
# A clause is satisfied when at least one literal is true.
# Literal x_i is true when x_i=1, ¬x_i when x_i=0.
# So clause (l1 ∨ l2 ∨ l3) is false only when all literals are false.
# So the clause is unsatisfied iff: for each literal, if it's x_i then x_i=0, if ¬x_i then x_i=1.
# So the clause polynomial can be defined as the indicator of the clause being FALSE.
# Then V_φ is the set of assignments where all clauses are FALSE — i.e., the formula is false.
# But we want the variety for the formula being true? Or the ideal generated by clauses?

# The conjecture says: "the affine variety defined by interpreting each clause as a degree-3 polynomial"
# — typically, one defines the ideal generated by the clause polynomials, and V_φ is the set of common zeros.

# But if we define f_c(x) = 1 if clause c is false at x, 0 otherwise, then f_c is a cubic polynomial.
# Then V_φ = {x | f_c(x) = 0 for all c} = {x | all clauses are true} = satisfying assignments.

# But then for unsatisfiable φ, V_φ = ∅.

# Then what is CH^1(∅)? Undefined, or trivial?

# Alternatively, sometimes people define the ideal generated by 1 - f_c, so that V_φ is where f_c=1, i.e., clause false.
# Then V_φ = {x | some clause is false} — which is everything if φ is not a tautology.

# This is confusing.

# Let's look at standard algebraic proof systems: one often defines the ideal generated by:
#   - clause polynomials: for clause (l1 ∨ l2 ∨ l3), use the product of (1 - l_i) where l_i is 0 or 1.
#   - and field equations: x_i² - x_i = 0.

# Then the ideal J_φ is generated by:
#   - for each clause: ∏_{literal in clause} (1 - literal_value)
#   - and x_i² - x_i for all i.

# Then V(J_φ) = set of satisfying assignments.

# So if φ is unsatisfiable, then V(J_φ) = ∅.

# Now, what is the Chow group of the empty set? Not defined.

# So this suggests that the variety V_φ must be defined differently.

# Another possibility: V_φ is the scheme defined by the ideal, even if empty.
# But Chow groups of empty scheme are zero.

# Alternatively, perhaps V_φ is the union of the solution sets of each clause? But that would be almost everything.

# Given the confusion, and the fact that for unsatisfiable 3-CNF:
#   - either V_φ is empty ⇒ CH^1(V_φ) undefined or trivial,
#   - or V_φ is zero-dimensional ⇒ CH^1(V_φ)=0,
# in both cases |CH^1(V_φ)[2]| is 1 (if we take trivial group) or 0 (if empty group) — but group order is at least 1.

# But if |CH^1(V_φ)[| = 1, then log₂(1+1)=1, and resolution width ≥1 — true.

# If |CH^1(V_φ)[2]| = 0, then log₂(0+1)=0, and width ≥0 — true.

# So the inequality holds trivially.

# However, the test strategy mentions "compute the zero-dimensional variety V_φ", implying it's non-empty.
# But for unsatisfiable φ, it should be empty.

# This is a contradiction.

# Therefore, the conjecture as stated contains a fundamental flaw: for unsatisfiable φ, V_φ is empty,
# so CH^1(V_φ) is not defined, or trivial, making the bound trivial.

# But let's suppose they meant the variety defined by the clause polynomials in a different way.

# Alternative interpretation: perhaps V_φ is the variety in a larger space, or they mean the ideal's structure.

# Given the time, and the fact that the mathematical setup appears inconsistent,
# we must conclude the conjecture is either trivial or ill-posed.

# However, to follow the test strategy, we try to compute something.

# The test strategy says: "generate all 3-CNF formulas with up to 3n clauses" for n≤8.

# But "all" is too many: for n=8, number of 3-clauses is C(16,3) ≈ 560, and up to 24 clauses — too many.

# Instead, we sample.

# But the core issue remains: what is CH^1(V_φ) for a zero-dim (or empty) variety?

# After research: in algebraic geometry, for a zero-dimensional scheme, the Chow group CH_0 is the free abelian group on the points (over algebraically closed field), but CH^1 is 0.

# So we proceed to test with small n, but we must define:
#   - How to compute CH^1(V_φ)[2]?

# The test strategy says: "construct the group of 0-cycles Z^0(V_φ)" — but 0-cycles are for CH_0, not CH^1.

# This suggests a typo: perhaps they meant CH_0(V_φ)[2], the 2-torsion of the zero-cycle group?

# But CH_0 for a zero-dim scheme is just the free group on points, so over ℤ, it's free abelian, so 2-torsion is trivial unless we reduce mod 2.

# But the Chow group is usually over ℤ.

# Alternatively, they might be working with Chow groups with 𝔽_2 coefficients.

# But the notation CH^1(V_φ)[2] means 2-torsion, not coefficients.

# Given the confusion, and the fact that the mathematical objects are not standardly defined in this context,
# we cannot reliably compute CH^1(V_φ)[2].

# Therefore, we must conclude the conjecture is not well-posed.

# However, to satisfy the requirement, we generate a few small unsatisfiable 3-CNFs,
# compute their minimum resolution width, and try to define a "CH^1" group.

# But we have no way to compute CH^1(V_φ)[2] as described.

# We note that for unsatisfiable φ, V_φ = ∅, so we set |CH^1(V_φ)[2]| = 1 (trivial group) or 0.

# Let's assume |CH^1(V_φ)[2]| = 1 for all unsatisfiable φ (by fiat), then log₂(1+1)=1.

# We then check if min resolution width ≥ 1 — which is always true.

# So the conjecture holds.

# But this is not a real test.

# Alternatively, suppose they meant the ideal's syzygy or homology?

# Given the time, we output a program that:
#   - generates a few small unsatisfiable 3-CNF formulas
#   - computes their minimum resolution width (via DPLL-based width search)
#   - sets |CH^1(V_φ)[2]| = 1 (since V_φ is empty or zero-dim)
#   - checks width >= 1

# This will always hold.

# But we must be honest.

# We choose to report the flaw.

print("INFO: The conjecture appears to be ill-posed.")
print("INFO: For an unsatisfiable 3-CNF φ, the variety V_φ ⊆ (𝔽_2)^n of satisfying assignments is empty.")
print("INFO: The Chow group CH^1 of the empty set is not defined, or trivial.")
print("INFO: For zero-dimensional varieties, CH^1 is trivial (no codimension-1 cycles).")
print("INFO: Thus |CH^1(V_φ)[2]| is 1 (trivial group) or 0 (empty), so log₂(|CH^1|+1) ≤ 1.")
print("INFO: Minimum resolution width is at least 1 for any non-empty refutation, so the inequality holds trivially.")
print("INFO: However, this makes the conjecture uninteresting and likely not what was intended.")
print("INFO: The test strategy mentions computing 0-cycles for CH^1, which is a sign of confusion between CH_0 and CH^1.")
print("INFO: We therefore cannot meaningfully test the conjecture as stated.")

# But to follow the instruction, we do a minimal computation.

# We'll take one known unsatisfiable 3-CNF: the pigeonhole principle for 2 pigeons in 1 hole.
# But that's not 3-CNF. We need 3-CNF.

# Example: n=3, formula: (x1∨x2∨x3) ∧ (x1∨x2∨¬x3) ∧ (x1∨¬x2∨x3) ∧ (x1∨¬x2∨¬x3) ∧ (¬x1∨x2∨x3) ∧ (¬x1∨x2∨¬x3) ∧ (¬x1∨¬x2∨x3) ∧ (¬x1∨¬x2∨¬x3)
# This is all 8 clauses — it's unsatisfiable? No, wait: it includes both x1 and ¬x1 in different clauses, but that doesn't make it unsat.
# Actually, it's the complete set of clauses of size 3 on 3 variables — it's unsatisfiable only if every assignment violates at least one clause.
# But each assignment satisfies exactly one clause? No: an assignment satisfies a clause if at least one literal is true.
# For example, (0,0,0) satisfies only the clause (¬x1∨¬x2∨¬x3)? No: (¬x1∨¬x2∨¬x3) is true when at least one of ¬x1,¬x2,¬x3 is true — which is always except (1,1,1).
# Actually, every assignment satisfies many clauses.

# The only way to have an unsatisfiable 3-CNF is to have a contradiction that forces no assignment to satisfy all clauses.

# Classic example: use a small contradiction.

# We can use: 
#   φ = (x) ∧ (¬x) ∧ (y∨y∨y)  — but not 3-CNF.

# To make 3-CNF, we can use:
#   (x ∨ a ∨ b) ∧ (¬x ∨ a ∨ b) ∧ (¬a) ∧ (¬b)
# But then we have 1-literals.

# We can expand: 
#   (¬a) becomes (¬a ∨ ¬a ∨ ¬a), similarly for ¬b.

# So let:
#   C1: (x ∨ a ∨ b)
#   C2: (¬x ∨ a ∨ b)
#   C3: (¬a ∨ ¬a ∨ ¬a) ≡ (¬a)
#   C4: (¬b ∨ ¬b ∨ ¬b) ≡ (¬b)

# Now, from C3 and C4, a=0, b=0.
# Then C1: x ∨ 0 ∨ 0 => x
# C2: ¬x ∨ 0 ∨ 0 => ¬x
# So we have x and ¬x — unsatisfiable.

# Variables: x, a, b → n=3.

# We compute minimum resolution width for this φ.

# We'll write a minimal DPLL-based width search.

def resolve(c1, c2):
    # c1, c2 are sets of literals
    # find a literal l such that l in c1 and ¬l in c2
    resolvents = []
    for l in c1:
        neg_l = ('¬'+l if not l.startswith('¬') else l[1:])
        if neg_l in c2:
            resolvent = (c1 - {l}) | (c2 - {neg_l})
            resolvents.append(resolvent)
    return resolvents

def min_resolution_width(clauses):
    # clauses: list of sets of literals
    # We want the minimum width (max clause size in refutation) over all resolution refutations.
    # We do a BFS on the set of clauses we can derive, but we must avoid infinite growth.
    # We use the fact that we only care about refutations (deriving empty clause).
    # We do iterative deepening on the maximum allowed width.
    # But we want minimum width, so we try width = 1,2,3,... until we find a refutation.

    # But width is the maximum clause size in the refutation.
    # We do iterative deepening on width.

    # However, for small n, we can do it.

    # We'll do: for w from 1 to some limit, try to derive empty clause using only clauses of size ≤ w.

    # But we can derive larger clauses and then resolve to smaller? No: resolution of two clauses of size k,l produces a clause of size k+l-2.
    # So to get small clauses, we might need large intermediate clauses.

    # Actually, we want the minimum W such that there exists a refutation where every clause has size ≤ W.

    # This is the standard width.

    # We do: start with original clauses.
    # Then repeatedly resolve pairs of clauses that have a complementary literal, and add the resolvent if its size ≤ current W.
    # We try W = 1,2,3,... until we derive the empty clause.

    # But this is not complete: sometimes you need to derive a clause of size > W to eventually get to empty clause with size ≤ W? 
    # No: if you have a refutation with max width W, then all clauses in it have size ≤ W.

    # So we can do:

    for W in range(1, 100):
        # Start with clauses of size ≤ W
        derived = [clause for clause in clauses if len(clause) <= W]
        # We'll use a set of frozensets to represent derived clauses
        seen = set(frozenset(clause) for clause in derived)
        # Queue for BFS? But we can just iterate until no new clauses
        changed = True
        while changed:
            changed = False
            new_clauses = []
            for i in range(len(derived)):
                for j in range(i+1, len(derived)):
                    resolvents = resolve(derived[i], derived[j])
                    for res in resolvents:
                        if len(res) <= W:
                            f_res = frozenset(res)
                            if f_res not in seen:
                                seen.add(f_res)
                                new_clauses.append(res)
                                changed = True
            derived.extend(new_clauses)
            if frozenset() in seen:
                return W
    return None

# Define our formula
# Variables: x, a, b
# Clauses:
#   C1: {x, a, b}
#   C2: {¬x, a, b}
#   C3: {¬a} -> but we need 3-literals: so {¬a, ¬a, ¬a} -> set removes duplicates -> {¬a}
# But sets don't allow duplicates. So we must allow multisets? But resolution doesn't care.

# However, in resolution, clauses are sets of literals.

# So we can have:
#   C1: {'x','a','b'}
#   C2: {'¬x','a','b'}
#   C3: {'¬a'}   -> but this is size 1, not 3.

# To make it 3-CNF, we can use auxiliary variables or repeat literals.

# But repeating literals doesn't change the clause: (¬a ∨ ¬a ∨ ¬a) ≡ (¬a)

# So in set representation, it's {'¬a'}.

# But the formula is not 3-CNF in the strict sense if we have clauses of size <3.

# We can pad with new variables? But that changes the formula.

# Alternatively, use a known 3-CNF unsatisfiable formula.

# We use the smallest known: the pigeonhole principle for 2 pigeons in 1 hole, converted to 3-CNF.

# PHP: two pigeons, one hole.
# Pigeons: p1, p2; hole: h1.
# Each pigeon must be in a hole: but only one hole.
# So: p1 must be in h1 -> clause: (h1_p1)
#      p2 must be in h1 -> clause: (h1_p2)
# But only one pigeon per hole: so not (h1_p1 and h1_p2) -> clause: (¬h1_p1 ∨ ¬h1_p2)

# So formula: (h1_p1) ∧ (h1_p2) ∧ (¬h1_p1 ∨ ¬h1_p2)

# Now convert to 3-CNF: we have clauses of size 1 and 2.

# We can use the transformation: 
#   (a) becomes (a ∨ a ∨ a) -> {'a'}
#   (a ∨ b) becomes (a ∨ b ∨ b) -> {'a','b'}

# So:
#   C1: {'h1_p1'}
#   C2: {'h1_p2'}
#   C3: {'¬h1_p1', '¬h1_p2'}

# But again, not all size 3.

# We can introduce new variables.

# Standard way: for a clause (a), we can write:
#   (a ∨ x ∨ y) ∧ (a ∨ x ∨ ¬y) ∧ (a ∨ ¬x ∨ y) ∧ (a ∨ ¬x ∨ ¬y)
# But that's equivalent to a.

# But that's 4 clauses.

# For our purpose, we allow clauses of size <3, as they can be seen as 3-CNF with repeated literals.

# But in set representation, we lose the repetition.

# We decide to work with general CNF, and the resolution system works the same.

# So our formula:
clauses = [
    {'x', 'a', 'b'},
    {'¬x', 'a', 'b'},
    {'¬a'},
    {'¬b'}
]

# But wait, we have {'¬a'} and {'¬b'}, which are size 1.

# We run min_resolution_width.

width = min_resolution_width(clauses)
print(f"INFO: min resolution width for example formula: {width}")
