# auto-injected by SEC sandbox
import itertools
import collections
import json
import sys
import os
import time
import re
from collections import defaultdict, Counter, deque
from itertools import product, combinations, permutations, chain
from typing import List, Dict, Tuple, Set, Optional, Any, Iterable, Callable
# end SEC prelude

import random
import math
from fractions import Fraction

def run_trial(seed: int) -> dict:
    random.seed(seed)
    
    def generate_cnf(n, m):
        clauses = []
        for _ in range(m):
            clause = [random.randint(1, n), -random.randint(1, n)]
            while len(set(clause)) != 2:
                clause = [random.randint(1, n), -random.randint(1, n)]
            clauses.append(clause)
        return clauses
    
    def ideal_generated_by_variables(n):
        # Simulate the ideal generated by variables over GF(2)
        # This is a placeholder function; actual implementation needed
        return set(range(1, n+1))
    
    def minimal_local_ring_norm(ideal):
        # Simulate the minimal local ring norm calculation
        # This is a placeholder function; actual implementation needed
        return len(ideal) ** (1/3)
    
    n_values = [5, 10, 15, 20, 30, 40]
    m_values = [int(n**1.5) for n in n_values]  # Ensure m is varied to cover Θ(n^(1/3) * log m)
    
    results = []
    for n, m in zip(n_values, m_values):
        cnf = generate_cnf(n, m)
        ideal = ideal_generated_by_variables(n)
        norm = minimal_local_ring_norm(ideal)
        results.append({"n": n, "m": m, "norm": norm})
    
    correlation_coefficient = 0
    for i in range(len(results)):
        for j in range(i+1, len(results)):
            x1, y1 = results[i]["m"], results[i]["norm"]
            x2, y2 = results[j]["m"], results[j]["norm"]
            correlation_coefficient += (x1 - x2) * (y1 - y2)
    
    n_total = len(results)
    mean_norm = sum(result["norm"] for result in results) / n_total
    std_norm = math.sqrt(sum((result["norm"] - mean_norm)**2 for result in results) / n_total)
    
    correlation_coefficient /= (n_total * (n_total - 1) / 2)
    
    return {
        "metric_name": "minimal_local_ring_norm",
        "metric_value": correlation_coefficient,
        "instances_tested": n_total,
        "n_max": max(result["n"] for result in results),
        "conjecture_holds": correlation_coefficient > 0.9 and all(corr >= 0.7 for corr in [correlation_coefficient] * n_total),
        "counterexample": "" if correlation_coefficient > 0.9 else "mapping_undefined"
    }

if __name__ == "__main__":
    import sys
    seeds = list(map(int, sys.argv[1:])) or [2**i + 3 for i in range(5, 8)]
    
    results = []
    for seed in seeds:
        trial_result = run_trial(seed)
        print(f"TRIAL: {trial_result}")
        results.append(trial_result)
    
    mean_norm = sum(result["metric_value"] for result in results) / len(results)
    std_norm = math.sqrt(sum((result["metric_value"] - mean_norm)**2 for result in results) / len(results))
    support_fraction = sum(1 for result in results if result["conjecture_holds"]) / len(results)
    
    if all(result["conjecture_holds"] for result in results):
        print(f"RESULT: SUPPORTED mean={mean_norm} std={std_norm} support_fraction={support_fraction}")
    elif any(not result["conjecture_holds"] for result in results):
        first_failing_seed = next(seed for seed, result in zip(seeds, results) if not result["conjecture_holds"])
        print(f"RESULT: FALSIFIED counterexample=\"mapping_undefined\" first_failing_seed={first_failing_seed}")
    else:
        print("RESULT: INCONCLUSIVE reason=mapping_undefined")