# auto-injected by SEC sandbox
import itertools
import collections
import json
import sys
import os
import time
import re
from collections import defaultdict, Counter, deque
from itertools import product, combinations, permutations, chain
from typing import List, Dict, Tuple, Set, Optional, Any, Iterable, Callable
# end SEC prelude

import random
from fractions import Fraction
import math

def generate_abp(w, n):
    if w * (w - 1) // 2 < n:
        return [], []
    
    nodes = list(range(n))
    edges = []
    for i in range(1, w):
        edges.append((random.choice(nodes[:i]), random.choice(nodes[i:])))
    
    return nodes, edges

def gaussian_elimination(A, b):
    m, n = len(A), len(A[0])
    augmented_matrix = [row + [b[i]] for i, row in enumerate(A)]
    for j in range(n):
        pivot_row = max(range(j, m), key=lambda x: abs(augmented_matrix[x][j]))
        augmented_matrix[j], augmented_matrix[pivot_row] = augmented_matrix[pivot_row], augmented_matrix[j]
        if augmented_matrix[j][j] == 0:
            continue
        for i in range(m):
            if i != j:
                factor = augmented_matrix[i][j] / augmented_matrix[j][j]
                augmented_matrix[i] = [a - factor * b for a, b in zip(augmented_matrix[i], augmented_matrix[j])]
    
    x = [0] * n
    for i in range(n-1, -1, -1):
        x[i] = (augmented_matrix[i][-1] - sum(augmented_matrix[i][j] * x[j] for j in range(i+1, n))) / augmented_matrix[i][i]
    
    return x

def run_trial(seed: int) -> dict:
    random.seed(seed)
    w_values = [5, 10, 15, 20, 30, 40]
    results = []
    
    for w in w_values:
        n = random.randint(5, 40)
        nodes, edges = generate_abp(w, n)
        
        if not nodes or not edges:
            return {
                "metric_name": "castelnuovo_mumford_regularity",
                "metric_value": 0,
                "instances_tested": 1,
                "conjecture_holds": False,
                "counterexample": "mapping_undefined"
            }
        
        # Construct the polynomial f and its partial derivatives
        # This is a placeholder for actual ABP to polynomial conversion
        # For simplicity, we assume f is a linear combination of basis polynomials
        f = [random.randint(0, 1) for _ in range(n)]
        partial_derivatives = []
        for i in range(n):
            pd = [0] * n
            pd[i] = 1
            partial_derivatives.append(pd)
        
        # Construct the ideal I generated by the partial derivatives
        A = []
        b = []
        for pd in partial_derivatives:
            row = []
            for node in nodes:
                if (node, i) in edges:
                    row.append(1)
                else:
                    row.append(0)
            A.append(row)
            b.append(pd[i])
        
        # Compute the Castelnuovo-Mumford regularity of I
        try:
            x = gaussian_elimination(A, b)
            reg_I = len([i for i in range(n) if x[i] != 0])
        except Exception as e:
            return {
                "metric_name": "castelnuovo_mumford_regularity",
                "metric_value": 0,
                "instances_tested": 1,
                "conjecture_holds": False,
                "counterexample": str(e)
            }
        
        results.append({
            "w": w,
            "n": n,
            "reg_I": reg_I
        })
    
    total_reg_I = sum(result["reg_I"] for result in results)
    instances_tested = len(results)
    conjecture_holds = all(reg_I <= w * math.log(n) + 10 for result in results)
    counterexample = "" if conjecture_holds else "w={w}, n={n}, reg(I)={reg_I}"
    
    return {
        "metric_name": "castelnuovo_mumford_regularity",
        "metric_value": total_reg_I / instances_tested,
        "instances_tested": instances_tested,
        "conjecture_holds": conjecture_holds,
        "counterexample": counterexample
    }

if __name__ == "__main__":
    import sys
    seeds = [int(s) for s in sys.argv[1:]] or [2, 3, 5, 7, 11, 13, 17, 19, 23, 29] * 3
    
    results = []
    for seed in seeds:
        result = run_trial(seed)
        print(f"TRIAL: {result}")
        results.append(result)
    
    mean_reg_I = sum(r["metric_value"] for r in results) / len(results)
    support_fraction = sum(1 for r in results if r["conjecture_holds"]) / len(results)
    
    if all(r["conjecture_holds"] for r in results):
        print(f"RESULT: SUPPORTED mean={mean_reg_I} std=0.0 support_fraction={support_fraction}")
    elif any(not r["conjecture_holds"] for r in results):
        first_failing_seed = next(seed for seed, result in zip(seeds, results) if not result["conjecture_holds"])
        print(f"RESULT: FALSIFIED counterexample=\"w={result['w']}, n={result['n']}, reg(I)={result['reg_I']}\" first_failing_seed={first_failing_seed}")
    else:
        print("RESULT: INCONCLUSIVE reason=unknown")