# auto-injected by SEC sandbox
import math
import itertools
import collections
import json
import sys
import os
import time
import re
from collections import defaultdict, Counter, deque
from itertools import product, combinations, permutations, chain
from typing import List, Dict, Tuple, Set, Optional, Any, Iterable, Callable
# end SEC prelude

import random
from fractions import Fraction

def gcd(a, b):
    while b:
        a, b = b, a % b
    return a

def lcm(a, b):
    return abs(a * b) // gcd(a, b)

def matrix_multiply(A, B):
    m, n, p = len(A), len(B), len(B[0])
    C = [[0] * p for _ in range(m)]
    for i in range(m):
        for j in range(p):
            for k in range(n):
                C[i][j] += A[i][k] * B[k][j]
    return C

def gaussian_elimination(A, b):
    m, n = len(A), len(b)
    Augmented = [A[i] + [b[i]] for i in range(m)]
    for i in range(m):
        max_row = i
        for j in range(i+1, m):
            if abs(Augmented[j][i]) > abs(Augmented[max_row][i]):
                max_row = j
        Augmented[i], Augmented[max_row] = Augmented[max_row], Augmented[i]
        pivot = Augmented[i][i]
        for j in range(i, n+1):
            Augmented[i][j] /= pivot
        for j in range(m):
            if j != i:
                factor = Augmented[j][i]
                for k in range(i, n+1):
                    Augmented[j][k] -= factor * Augmented[i][k]
    return [row[-1] for row in Augmented]

def partial_derivatives(f, vars, x_values):
    def diff(f, var):
        h = 1e-6
        f_plus = eval(f.replace(var, str(x + h)))
        f_minus = eval(f.replace(var, str(x - h)))
        return (f_plus - f_minus) / (2 * h)
    
    partials = []
    for var in vars:
        partial = diff(f, var)
        partials.append(partial)
    return partials

def run_trial(seed: int) -> dict:
    random.seed(seed)
    n = random.randint(5, 40)
    w = random.randint(2, 10)
    GF2 = [0, 1]
    
    # Generate a random ABP of width w over GF(2)
    def generate_abp(w):
        if w == 1:
            return [[random.choice(GF2)]]
        else:
            left = generate_abp(w - 1)
            right = generate_abp(w - 1)
            return [left + right, left + right, left + right, left + right]
    
    abp = generate_abp(w)
    
    # Convert ABP to polynomial
    def abp_to_poly(abp):
        if len(abp) == 1:
            return str(abp[0][0])
        else:
            left = abp_to_poly(abp[:len(abp)//2])
            right = abp_to_poly(abp[len(abp)//2:])
            return f"({left} + {right})"
    
    poly_str = abp_to_poly(abp)
    vars = [f"x{i}" for i in range(n)]
    x_values = [random.choice(GF2) for _ in range(n)]
    
    # Compute partial derivatives
    partials = partial_derivatives(poly_str, vars, x_values)
    
    # Construct the ideal I generated by the partial derivatives
    I = []
    for p in partials:
        I.append(p)
    
    # Calculate the Castelnuovo-Mumford regularity of I using Gröbner basis algorithms
    try:
        reg_I = len(gaussian_elimination(I, [0] * len(I)))
    except Exception as e:
        return {
            "metric_name": "castelnuovo_mumford_regularity",
            "metric_value": 0,
            "instances_tested": 1,
            "conjecture_holds": False,
            "counterexample": str(e)
        }
    
    # Verify the conjecture
    if reg_I <= w * math.log(n, 2) + 10:
        return {
            "metric_name": "castelnuovo_mumford_regularity",
            "metric_value": reg_I,
            "instances_tested": 1,
            "conjecture_holds": True,
            "counterexample": ""
        }
    else:
        return {
            "metric_name": "castelnuovo_mumford_regularity",
            "metric_value": reg_I,
            "instances_tested": 1,
            "conjecture_holds": False,
            "counterexample": f"w={w}, n={n}, reg(I)={reg_I}"
        }

if __name__ == "__main__":
    import sys
    seeds = [int(s) for s in sys.argv[1:]] or [2**i - 1 for i in range(5, 8)]
    
    results = []
    for seed in seeds:
        result = run_trial(seed)
        print(f"TRIAL: {result}")
        results.append(result)
    
    mean_reg_I = sum(r['metric_value'] for r in results) / len(results)
    support_fraction = sum(1 for r in results if r['conjecture_holds']) / len(results)
    
    if all(r['conjecture_holds'] for r in results):
        print(f"RESULT: SUPPORTED mean={mean_reg_I} std=0.0 support_fraction={support_fraction}")
    elif support_fraction >= 0.8:
        print(f"RESULT: SUPPORTED mean={mean_reg_I} std=0.0 support_fraction={support_fraction}")
    else:
        first_failing_seed = next(r['seed'] for r in results if not r['conjecture_holds'])
        print(f"RESULT: FALSIFIED counterexample=\"w={results[0]['w']}, n={results[0]['n']}, reg(I)={results[0]['reg_I']}\" first_failing_seed={first_failing_seed}")