import random
import itertools
from typing import List, Tuple, Set, Dict, Generator, Optional
from functools import reduce
from collections import defaultdict
import copy

# We are working over F2
F2 = 2

# Use a fixed random seed for reproducibility
rng = random.Random(42)

def polynomial_str(poly: Tuple[int, ...]) -> str:
    """Convert a multilinear monomial (as tuple of exponents mod 2) to string."""
    vars = [f"x{i+1}" for i, e in enumerate(poly) if e == 1]
    return "*".join(vars) if vars else "1"

def multidegree(poly: Tuple[int, ...]) -> int:
    """Return total degree of a multilinear monomial."""
    return sum(poly)

def multilinear_mul_F2(a: Tuple[int, ...], b: Tuple[int, ...], n: int) -> Tuple[int, ...]:
    """Multiply two multilinear monomials over F2[x1,...,xn], result is multilinear (square-free)."""
    res = list(a)
    for i in range(n):
        if b[i]:
            res[i] = (res[i] + b[i]) % 2
    return tuple(res)

def generate_clause_polynomial(clause: Tuple[int, int, int], n: int) -> Tuple[int, ...]:
    """Given a clause (i,j,k) meaning ¬x_i ∨ ¬x_j ∨ ¬x_k, return the polynomial 1 + x_i + x_j + x_k over F2.
    Variables are 1-indexed in input, we convert to 0-indexed.
    The polynomial is represented as a set of monomials (each as tuple of exponents mod 2).
    So 1 -> (0,0,...,0), x_i -> (0,...,1,...,0) at position i.
    Returns the *support* of the polynomial: the set of monomials with coefficient 1.
    """
    monomials = []
    # constant term
    const = tuple(0 for _ in range(n))
    monomials.append(const)
    # x_i term
    if clause[0] != 0:
        v1 = abs(clause[0]) - 1
        mono1 = tuple(1 if i == v1 else 0 for i in range(n))
        monomials.append(mono1)
    if clause[1] != 0:
        v2 = abs(clause[1]) - 1
        mono2 = tuple(1 if i == v2 else 0 for i in range(n))
        monomials.append(mono2)
    if clause[2] != 0:
        v3 = abs(clause[2]) - 1
        mono3 = tuple(1 if i == v3 else 0 for i in range(n))
        monomials.append(mono3)
    return monomials

def reduce_polynomial_F2(poly: Set[Tuple[int, ...]], gb: List[Set[Tuple[int, ...]]], n: int) -> Set[Tuple[int, ...]]:
    """Reduce a polynomial (as set of monomials) modulo a Gröbner basis over F2.
    Uses multidegrevlex order: first by total degree (high), then reverse lex (low vars first).
    """
    poly = set(poly)
    changed = True
    while changed and poly:
        changed = False
        # Sort GB elements by leading term (largest first)
        # We compute leading term as the largest monomial under degrevlex
        gb_sorted = sorted(gb, key=lambda g: (sum(max(g, key=multidegree)), 
                                              [-m[i] for i in range(n-1,-1,-1) for m in [max(g, key=multidegree)]]), reverse=True)
        for g in gb_sorted:
            if not g:
                continue
            # Leading term of g: largest monomial in g
            lt_g = max(g, key=multidegree)
            # Find if any term in poly is divisible by lt_g
            for term in poly:
                # In multilinear ring, divisibility means: support of lt_g ⊆ support of term
                if all(lt_g[i] == 0 or term[i] == 1 for i in range(n)):
                    # Multiply g by (term / lt_g)
                    quotient = tuple(term[i] ^ lt_g[i] for i in range(n))  # since F2 and multilinear
                    g_shifted = {multilinear_mul_F2(m, quotient, n) for m in g}
                    # Subtract (XOR) g_shifted from poly
                    poly = poly.symmetric_difference(g_shifted)
                    changed = True
                    break
                if changed:
                    break
            if changed:
                break
    return poly

def compute_groebner_basis_F2(polynomials: List[Set[Tuple[int, ...]]], n: int) -> List[Set[Tuple[int, ...]]]:
    """Compute a Gröbner basis for the ideal generated by polynomials over F2.
    Uses Buchberger's algorithm with multidegrevlex.
    Each polynomial is a set of monomials (coefficient 1 in F2).
    """
    gb = [set(p) for p in polynomials if p]
    if not gb:
        return gb
    # Remove zero polynomials
    gb = [p for p in gb if p]
    pairs = [(i, j) for i in range(len(gb)) for j in range(i+1, len(gb))]
    while pairs:
        i, j = pairs.pop(0)
        f = gb[i]
        g = gb[j]
        # Compute S-polynomial
        # Find lcm of leading terms
        lt_f = max(f, key=multidegree)
        lt_g = max(g, key=multidegree)
        # lcm: componentwise max
        lcm = tuple(max(lt_f[i], lt_g[i]) for i in range(n))
        # quotient1 = lcm / lt_f
        quotient1 = tuple(lcm[i] ^ lt_f[i] for i in range(n))
        # quotient2 = lcm / lt_g
        quotient2 = tuple(lcm[i] ^ lt_g[i] for i in range(n))
        # spoly = (lcm // lt_f) * f + (lcm // lt_g) * g
        spoly = set()
        for m in f:
            spoly.add(multilinear_mul_F2(m, quotient1, n))
        for m in g:
            spoly.add(multilinear_mul_F2(m, quotient2, n))
        # Reduce spoly modulo gb
        reduced = reduce_polynomial_F2(spoly, gb, n)
        if reduced and reduced != set():
            # Add to gb
            gb.append(reduced)
            # Add new pairs
            for k in range(len(gb)-1):
                pairs.append((k, len(gb)-1))
    # Minimize and interreduce?
    # For now, return as is
    return gb

def compute_castelnuovo_mumford_regularity(gb: List[Set[Tuple[int, ...]]], n: int) -> int:
    """Approximate the Castelnuovo-Mumford regularity of R/I.
    For a homogeneous ideal, reg(R/I) = max { deg(m) - i | m in minimal generators of i-th syzygy module }.
    But we don't have full resolution. However, for a Gröbner basis, one can use:
    reg(I) = max_{g in GB} deg(lt(g))  ??? Not exactly.
    
    Actually, for a homogeneous ideal, the regularity of R/I is the maximum over i of { a_i - i }
    where a_i is the maximal degree of a generator in the i-th syzygy module.
    
    But we don't compute syzygies. However, there is a known bound:
    If G is a Gröbner basis, then reg(I) <= max_{g in G} deg(g)
    But this is not exact.
    
    Alternative: For a monomial ideal, reg(R/I) = max degree of a minimal generator of the Stanley-Reisner ideal?
    But our ideal is not monomial.
    
    Actually, in the multilinear setting over F2, and since all clause polynomials are degree at most 3,
    and the ring is Artinian, we can try to compute the Hilbert function and deduce regularity?
    
    However, the conjecture is likely false for small n, so we can use a simpler proxy:
    Since the ideal is generated in degree <=3, and we are in a 0-dimensional ring, the regularity is finite.
    But computing full minimal free resolution is too hard without libraries.
    
    Given the test strategy says "use minimal Gröbner basis to approximate", we assume:
    reg(I_φ) = max{ deg(lt(g)) for g in minimal Gröbner basis } 
    but this is reg(I), not reg(R/I). Actually, reg(R/I) = reg(I) - 1? Not exactly.
    
    Standard fact: reg(R/I) = max { deg(m) | m is a minimal generator of the initial ideal } 
    but only if the initial ideal is componentwise linear? Not in general.
    
    Another fact: reg(R/I) is the maximum over all i of { a_i - i } where a_i is the maximal degree
    in the i-th step of the minimal free resolution of R/I.
    
    But we cannot compute that.
    
    However, for 0-dimensional ideals, reg(R/I) = max { deg(m) | m is a standard monomial } 
    ??? No, that's the degree.
    
    Actually, in 0-dimensional case, the regularity is the maximal degree of a non-killed monomial?
    But no: regularity can be less than the socle degree.
    
    Given the complexity and the fact that we are only testing small n (<=4), we can compute the minimal free resolution
    by brute force? But that's very hard.
    
    Alternatively, we use the following known fact:
    For a homogeneous ideal I in a polynomial ring, reg(R/I) = max { j - i | Tor_i(R/I, k)_j ≠ 0 }
    
    But we cannot compute Tor.
    
    Given the constraints, and since the test strategy says "approximate", we use:
    reg(R/I) ≈ max degree of a polynomial in the reduced Gröbner basis?
    But this is not correct.
    
    Another idea: in the multilinear polynomial ring (exterior? no, it's F2[x]/(x^2-x)), the Castelnuovo-Mumford regularity
    might be defined via the degrees in the resolution.
    
    But without a proper implementation, and given the time, we must make a decision.
    
    Since the conjecture is likely to be falsified by a small counterexample, and the resolution width is at least 1 and at most n+1,
    we can compute the resolution width exactly and compare to a candidate algebraic invariant.
    
    Let us define:
      reg_candidate = max( deg(lt(g)) for g in gb )   if gb non-empty, else 0
    But this is for I, not R/I.
    
    Actually, reg(R/I) = reg(I) - 1 only if I is principal? No.
    
    Standard: reg(R/I) = reg(I) - 1 is false.
    
    In fact, reg(R/I) = max { reg(I) - 1, 0 }? No.
    
    After checking: for any ideal I, reg(R/I) = reg(I) - 1 only if I is principal and generated in degree d, then reg(R/I)=d-1? 
    But no: if I=(x^2), then R/I has basis 1,x, so reg(R/I)=1, reg(I)=2, so 2-1=1, holds.
    If I=(x^2,y^2), then reg(I)=2, reg(R/I)=? The resolution is 0 <- R/I <- R <- R^2 <- R <- 0, with maps, degrees: 
    generators in deg 2, syzygy in deg 4? 
    Actually, minimal resolution: 
      R <- R^2 (deg 2) <- R (deg 4) 
    So reg(R/I) = max{0, 2-1, 4-2} = max{0,1,2}=2.
    And reg(I) = max{2, 4-1}=max{2,3}=3? 
    How is reg(I) defined? 
    reg(M) for module M is max { a_i - i } over i, where a_i is max degree in i-th syzygy.
    For I, resolution: 0 <- I <- R^2 <- R <- 0, with R^2 in deg 2, R in deg 4.
    So reg(I) = max{2-0, 4-1} = max{2,3}=3.
    Then reg(R/I)=2, reg(I)=3, so reg(R/I) = reg(I) - 1? 3-1=2, yes.
    Is this always true?
    In general, for any ideal I, the regularity of R/I and I are related by reg(R/I) = reg(I) - 1?
    But when I=R, reg(I)=0, reg(R/I)=reg(0)=-infinity? Not defined.
    For proper ideals, in a polynomial ring, we have a short exact sequence:
      0 -> I -> R -> R/I -> 0
    Then reg(R/I) <= max{ reg(R), reg(I)-1 } and reg(I) <= max{ reg(R), reg(R/I)+1 }
    And since reg(R)=0, we have reg(R/I) <= max{0, reg(I)-1} and reg(I) <= max{0, reg(R/I)+1}
    But this doesn't give equality.
    
    However, in the graded case, if I is generated in positive degree, then reg(R/I) = reg(I) - 1?
    The example above holds. Another: I=(x), then reg(I)=1, reg(R/I)=0, and 1-1=0, holds.
    I=(x,y), reg(I)=1, reg(R/I)=0, 1-1=0, holds.
    I=(x^3), reg(I)=3, reg(R/I)=2, 3-1=2, holds.
    So it seems reg(R/I) = reg(I) - 1.
    
    Therefore, we can compute reg(I) from the minimal free resolution of I, then subtract 1.
    
    But we don't have the resolution. However, there is a result: 
      reg(I) = max { deg(g) | g in minimal Gröbner basis of I } 
    is not true: in the (x^2,y^2) example, the Gröbner basis is {x^2,y^2}, max deg=2, but reg(I)=3.
    So we need the syzygies.
    
    Given the complexity and the small n (<=4 variables), we can compute the entire ring and the ideal membership.
    The ring has 2^n elements, so for n<=4, at most 16 elements.
    
    We can compute the standard monomials (monomials not in the initial ideal) and then compute the Hilbert function.
    But regularity is not directly the degree of the last standard monomial.
    
    For 0-dimensional ideals, the regularity is the smallest d such that all monomials of degree > d are in the ideal.
    But that's the index of regularity, which equals the regularity in the 0-dimensional case.
    Yes! For 0-dimensional ideals, the Castelnuovo-Mumford regularity of R/I is equal to the index of regularity, 
    which is the smallest integer r such that dim(R/I)_d = 0 for all d > r, but no: dim(R/I)_d is the Hilbert function,
    and for d large, it's 0, but the regularity is the maximum degree of a standard monomial? 
    Actually, in 0-dimensional case, the Hilbert function becomes 0 for d > max_deg, and the regularity is exactly 
    the maximum degree of a standard monomial.
    Is that true?
    In the example I=(x^2,y^2) in k[x,y], standard monomials: 1, x, y, xy, degrees 0,1,1,2. Max degree=2.
    And we computed reg(R/I)=2, yes.
    In I=(x^2) in k[x], standard monomials: 1, x, degrees 0,1. reg(R/I)=1, and max degree=1.
    So yes, for 0-dimensional ideals, reg(R/I) = max { deg(m) | m is a standard monomial }.
    
    Therefore, we can compute:
      1. Compute a Gröbner basis G for I.
      2. Compute the initial ideal: { leading terms of g in G }
      3. Find all monomials not in the initial ideal (standard monomials)
      4. reg(R/I) = max { deg(m) | m is a standard monomial }
    
    This is correct for 0-dimensional ideals.
    Our ideal I_φ is 0-dimensional because the ring is finite-dimensional (we are in a quotient by x_i^2 - x_i implicitly? 
    But wait: in the problem, we are in F2[x1,...,xn], not in the Boolean quotient.
    
    However, the clause polynomials do not include x_i^2 - x_i. So the ring is not Artinian.
    
    But in the context of SAT, one usually works in the Boolean ring F2[x1,...,xn]/(x1^2-x1, ..., xn^2-xn).
    The problem does not specify this quotient.
    
    Looking back: "the ideal in 𝔽₂[x₁,…,xₙ] generated by the clause polynomials"
    So it's in the full polynomial ring, not the Boolean quotient.
    
    But then the ideal is not 0-dimensional, and the regularity might be infinite? 
    However, the clause polynomials are not enough to make it 0-dimensional.
    
    This is a problem.
    
    But the rationale says "clause-variable structure induces a graded algebraic object", and regularity is defined.
    
    Perhaps we should work in the Boolean ring? But the problem does not say so.
    
    Alternatively, the polynomials are multilinear by construction? The clause polynomial 1+x_i+x_j+x_k is multilinear.
    And when we generate the ideal, we might stay in the multilinear polynomials? But no, multiplying two clause polynomials
    can give degree 6 terms.
    
    However, in F2, and since we are only interested in solutions in {0,1}^n, one usually adds the field equations x_i^2 = x_i.
    
    Given the context of SAT, it is standard to include the field equations.
    
    But the conjecture does not mention them.
    
    Let us re-read: "the ideal in 𝔽₂[x₁,…,xₙ] generated by the clause polynomials"
    So only the clause polynomials.
    
    But then for a satisfiable formula, the variety is infinite (a union of affine spaces), so not 0-dimensional.
    
    This is a critical point.
    
    However, the resolution width is defined for any 3-CNF, and the regularity should be finite.
    
    Perhaps the regularity is still defined as the maximum over the minimal resolution.
    
    But without the field equations, the ring is not Noetherian in the graded sense? It is, but the ideal may not be homogeneous.
    
    The clause polynomial 1+x_i+x_j+x_k is not homogeneous.
    
    So the ideal is not homogeneous, and Castelnuovo-Mumford regularity is typically defined for homogeneous ideals.
    
    This is a major issue.
    
    The conjecture might be intended for the homogenized ideal or for the ideal in the Boolean ring.
    
    Given the time, and since the test strategy says "generate all 3-CNF formulas with n<=4", and "compute the clause ideal",
    and the rationale mentions "logical inconsistency", it is likely that the intended ring is the Boolean ring.
    
    Therefore, we will include the field equations: x_i^2 + x_i = 0 for each i, which is x_i^2 - x_i = 0 in F2.
    But in F2, x_i^2 + x_i = 0.
    
    We add these to the ideal.
    
    Then the ring becomes finite-dimensional, and the ideal is 0-dimensional.
    
    This is standard in algebraic proof systems (e.g., Nullstellensatz, Polynomial Calculus).
    
    So we modify: I_φ is generated by:
      - for each clause ¬x_i ∨ ¬x_j ∨ ¬x_k: the polynomial 1 + x_i + x_j + x_k
      - for each variable x_i: the polynomial x_i^2 + x_i
    
    Then the variety is exactly the set of Boolean solutions.
    
    And the ideal is 0-dimensional.
    
    Then reg(R/I) = max degree of a standard monomial.
    
    We proceed with this.
    """
    # If no generators, then I=0, so R/I = R, but R is not 0-dimensional, but with field equations we have finite dim
    # But we have added field equations, so the ring is finite.
    # Compute initial ideal from GB
    if not gb:
        # Then I=0, so standard monomials are all monomials, but with field equations, we are in a quotient.
        # But we have field equations in the ideal, so we must have included them.
        # So gb should not be empty.
        pass
    # Get leading terms: for each g in gb, the largest monomial in g under degrevlex
    leading_terms = set()
    for g in gb:
        if g:
            lt = max(g, key=multidegree)
            leading_terms.add(lt)
    # Now, generate all possible monomials in n variables, multilinear (since field equations make x_i^2 = x_i, so we only consider square-free)
    # But in the polynomial ring, monomials can have high degree, but modulo field equations, every monomial is equivalent to a square-free one.
    # However, for Gröbner basis in the ring with field equations, we can restrict to square-free monomials.
    # But our GB is computed in the full ring, but we have included field equations, so the initial ideal will include x_i^2 for each i.
    # So any monomial with x_i^2 is reducible.
    # Therefore, we only need to consider square-free monomials, i.e., subsets of variables.
    all_monomials = []
    for bitmask in range(2**n):
        mono = tuple(1 if (bitmask >> i) & 1 else 0 for i in range(n))
        all_monomials.append(mono)
    # Standard monomials: those not divisible by any leading term
    # But "divisible" in the polynomial ring: a monomial m is divisible by lt if lt divides m, i.e., support(lt) ⊆ support(m) and exponents allow.
    # But since we are in a ring with x_i^2 = x_i, we should work in the quotient. However, our GB is for the ideal including field equations.
    # So the initial ideal contains x_i^2 for each i, so any monomial with exponent >=2 on any variable is in the initial ideal.
    # But our monomials are represented as 0/1, so they are square-free.
    # Now, a square-free monomial m is divisible by a square-free monomial lt if lt[i] <= m[i] for all i, i.e., support(lt) ⊆ support(m).
    standard_monomials = []
    for m in all_monomials:
        divisible = False
        for lt in leading_terms:
            if all(lt[i] == 0 or m[i] == 1 for i in range(n)):
                divisible = True
                break
        if not divisible:
            standard_monomials.append(m)
    if not standard_monomials:
        # This should not happen, since 1 is always standard if I is proper
        return 0
    max_deg = max(sum(m) for m in standard_monomials)
    return max_deg

def generate_all_3cnf_clauses(n: int) -> List[Tuple[int, int, int]]:
    """Generate all possible 3-CNF clauses on n variables.
    Each clause is a tuple of 3 literals, where literal is ±i (i from 1 to n), 0 means absent (for smaller clauses).
    But 3-CNF means exactly 3 literals.
    So we generate all ordered triples of distinct variables, and for each, all sign combinations.
    But clauses are sets, so order doesn't matter, and no duplicate variables.
    We generate combinations of 3 distinct variables, then for each, 2^3 = 8 sign combinations.
    Total: C(n,3)*8.
    """
    clauses = []
    if n < 3:
        return clauses
    for vars in itertools.combinations(range(1, n+1), 3):
        for signs in itertools.product([1, -1], repeat=3):
            clause = tuple(signs[i] * vars[i] for i in range(3))