# auto-injected by SEC sandbox
import itertools
import collections
import json
import sys
import os
import time
import re
from collections import defaultdict, Counter, deque
from itertools import product, combinations, permutations, chain
from fractions import Fraction
from typing import List, Dict, Tuple, Set, Optional, Any, Iterable, Callable
# end SEC prelude

import random
import math

def gcd(a, b):
    while b:
        a, b = b, a % b
    return a

def lcm(a, b):
    return abs(a*b) // gcd(a, b)

def matrix_mul(A, B, mod):
    m, n, p = len(A), len(B), len(B[0])
    C = [[0] * p for _ in range(m)]
    for i in range(m):
        for j in range(p):
            for k in range(n):
                C[i][j] += A[i][k] * B[k][j]
            C[i][j] %= mod
    return C

def matrix_pow(M, k, mod):
    result = [[0 if i != j else 1 for j in range(len(M))] for i in range(len(M))]
    while k > 0:
        if k % 2 == 1:
            result = matrix_mul(result, M, mod)
        M = matrix_mul(M, M, mod)
        k //= 2
    return result

def det(matrix, mod):
    n = len(matrix)
    if n == 1:
        return matrix[0][0]
    elif n == 2:
        return (matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]) % mod
    else:
        det_val = 0
        for j in range(n):
            sub_matrix = [row[:j] + row[j+1:] for row in matrix[1:]]
            det_val += (-1) ** j * matrix[0][j] * det(sub_matrix, mod)
        return det_val % mod

def minimal_local_ring_rank(matrix, mod):
    n = len(matrix)
    if n == 1:
        return 1
    elif n == 2:
        return 2 if matrix[0][0] != 0 or matrix[1][1] != 0 else 1
    else:
        for rank in range(1, n + 1):
            for i in range(n - rank + 1):
                for j in range(n - rank + 1):
                    sub_matrix = [row[j:j+rank] for row in matrix[i:i+rank]]
                    if det(sub_matrix, mod) != 0:
                        return rank
        return n

def run_trial(seed: int) -> dict:
    random.seed(seed)
    alpha = 2.5  # Example constant value for α
    instances_tested = 30
    n_max = 40
    conjecture_holds = True
    counterexample = ""

    for _ in range(instances_tested):
        n = random.randint(5, min(n_max, 30))
        rank_variance = random.uniform(1, n)
        boolean_functions = [[random.choice([0, 1]) for _ in range(n)] for _ in range(n)]
        
        # Compute the ideal generated by the Boolean functions
        ideal_matrix = []
        for i in range(n):
            row = [boolean_functions[j][i] for j in range(n)]
            ideal_matrix.append(row)
        
        # Determine the minimal local ring rank of the ideals
        rank = minimal_local_ring_rank(ideal_matrix, 2)
        
        if rank > alpha * rank_variance**2:
            conjecture_holds = False
            counterexample = f"n={n}, rank_variance={rank_variance}, rank={rank}"
    
    return {
        "metric_name": "minimal_local_ring_rank",
        "metric_value": alpha,
        "instances_tested": instances_tested,
        "n_max": n_max,
        "conjecture_holds": conjecture_holds,
        "counterexample": counterexample
    }

if __name__ == "__main__":
    import sys
    seeds = [int(arg) for arg in sys.argv[1:]] or [2**i + 7 for i in range(5, 30)]
    
    results = []
    for seed in seeds:
        result = run_trial(seed)
        print(f"TRIAL: {result}")
        results.append(result)
    
    mean_value = sum(r["metric_value"] for r in results) / len(results)
    std_value = math.sqrt(sum((r["metric_value"] - mean_value)**2 for r in results) / len(results))
    support_fraction = sum(1 for r in results if r["conjecture_holds"]) / len(results)
    
    if all(r["conjecture_holds"] for r in results):
        print(f"RESULT: SUPPORTED mean={mean_value} std={std_value} support_fraction={support_fraction}")
    elif any(not r["conjecture_holds"] for r in results) and support_fraction >= 0.8:
        first_failing_seed = next(r["seed"] for r in results if not r["conjecture_holds"])
        print(f"RESULT: FALSIFIED counterexample=\"{results[0]['counterexample']}\" first_failing_seed={first_failing_seed}")
    else:
        print(f"RESULT: INCONCLUSIVE reason=insufficient_evidence n_tested={len(seeds)}")