# auto-injected by SEC sandbox
import itertools
import collections
import json
import sys
import os
import time
import re
from collections import defaultdict, Counter, deque
from itertools import product, combinations, permutations, chain
from fractions import Fraction
from typing import List, Dict, Tuple, Set, Optional, Any, Iterable, Callable
# end SEC prelude

import random
import math

def run_trial(seed: int) -> dict:
    random.seed(seed)
    
    def is_prime(n):
        if n <= 1:
            return False
        for i in range(2, int(math.sqrt(n)) + 1):
            if n % i == 0:
                return False
        return True
    
    def generate_random_graph(n):
        edges = set()
        while len(edges) < n * (n - 1) // 2:
            u, v = random.sample(range(n), 2)
            if u != v and (u, v) not in edges and (v, u) not in edges:
                edges.add((u, v))
        return {i: [] for i in range(n)}, edges
    
    def matrix_multiply(A, B):
        m = len(A)
        n = len(B[0])
        p = len(B)
        C = [[0] * n for _ in range(m)]
        for i in range(m):
            for j in range(n):
                for k in range(p):
                    C[i][j] += A[i][k] * B[k][j]
        return C
    
    def gaussian_elimination(A, b):
        m = len(A)
        n = len(A[0])
        augmented_matrix = [A[i] + [b[i]] for i in range(m)]
        
        for pivot_row in range(n):
            if abs(augmented_matrix[pivot_row][pivot_row]) == 0:
                return None, None
            
            # Normalize the pivot row
            for j in range(pivot_row, n + 1):
                augmented_matrix[pivot_row][j] /= augmented_matrix[pivot_row][pivot_row]
            
            # Eliminate other rows
            for i in range(m):
                if i != pivot_row and abs(augmented_matrix[i][pivot_row]) > 0:
                    factor = augmented_matrix[i][pivot_row]
                    for j in range(pivot_row, n + 1):
                        augmented_matrix[i][j] -= factor * augmented_matrix[pivot_row][j]
        
        x = [0] * n
        for i in range(n - 1, -1, -1):
            x[i] = augmented_matrix[i][-1]
            for j in range(i + 1, n):
                x[i] -= augmented_matrix[i][j] * x[j]
        
        return x, None
    
    def determinant(A):
        m = len(A)
        if m == 1:
            return A[0][0]
        det = 0
        for j in range(m):
            submatrix = [row[:j] + row[j+1:] for row in A[1:]]
            det += (-1) ** j * A[0][j] * determinant(submatrix)
        return det
    
    def is_singular(A):
        return determinant(A) == 0
    
    def communication_complexity_rank(G):
        n = len(G)
        incidence_matrix = [[0] * n for _ in range(n)]
        for u, v in G[1]:
            incidence_matrix[u][v] = 1
            incidence_matrix[v][u] = 1
        
        rank = 0
        for i in range(n):
            row = [incidence_matrix[j][i] for j in range(n)]
            if any(row[j] != 0 for j in range(i)):
                rank += 1
        return rank
    
    def minimal_monodromy_group_order(G):
        n = len(G)
        incidence_matrix = [[0] * n for _ in range(n)]
        for u, v in G[1]:
            incidence_matrix[u][v] = 1
            incidence_matrix[v][u] = 1
        
        if is_singular(incidence_matrix):
            return float('inf'), "singular_matrix"
        
        # Find the stabilizer subgroup of S_n acting on columns of I_G
        stabilizer = []
        for perm in itertools.permutations(range(n)):
            permuted_matrix = [[0] * n for _ in range(n)]
            for i in range(n):
                for j in range(n):
                    permuted_matrix[i][j] = incidence_matrix[perm[i]][perm[j]]
            if permuted_matrix == incidence_matrix:
                stabilizer.append(perm)
        
        # The minimal monodromy group M_G is the subgroup generated by stabilizer
        m_g = len(stabilizer)
        return m_g, None
    
    n_values = [5, 10, 15, 20, 30, 40]
    results = []
    
    for n in n_values:
        G, edges = generate_random_graph(n)
        m_g, error = minimal_monodromy_group_order(G)
        
        if error == "singular_matrix":
            return {
                "metric_name": "minimal_monodromy_group_order",
                "metric_value": float('inf'),
                "instances_tested": 1,
                "n_max": n,
                "conjecture_holds": False,
                "counterexample": error
            }
        
        r_g = communication_complexity_rank(G)
        
        results.append({
            "n": n,
            "m_g": m_g,
            "r_g": r_g
        })
    
    mean_m_g = sum(result["m_g"] for result in results) / len(results)
    mean_r_g = sum(result["r_g"] for result in results) / len(results)
    
    conjecture_holds = all(result["m_g"] <= math.log(n, 2)**2 and result["r_g"] <= math.log(n, 2)**2 for result in results)
    counterexample = "" if conjecture_holds else "singular_matrix"
    
    return {
        "metric_name": "minimal_monodromy_group_order",
        "metric_value": mean_m_g,
        "instances_tested": len(results),
        "n_max": max(result["n"] for result in results),
        "conjecture_holds": conjecture_holds,
        "counterexample": counterexample
    }

if __name__ == "__main__":
    import sys
    seeds = [int(s) for s in sys.argv[1:]] or [2, 3, 5, 7, 11, 13, 17, 19, 23, 29] * 3
    
    results = []
    for seed in seeds:
        result = run_trial(seed)
        print(f"TRIAL: {result}")
        results.append(result)
    
    mean_metric_value = sum(result["metric_value"] for result in results) / len(results)
    support_fraction = sum(1 for result in results if result["conjecture_holds"]) / len(results)
    
    if all(result["conjecture_holds"] for result in results):
        print(f"RESULT: SUPPORTED mean={mean_metric_value} std=0.0 support_fraction={support_fraction}")
    elif support_fraction >= 0.8:
        print(f"RESULT: SUPPORTED mean={mean_metric_value} std=0.0 support_fraction={support_fraction}")
    else:
        first_failing_seed = next(seed for seed, result in zip(seeds, results) if not result["conjecture_holds"])
        print(f"RESULT: FALSIFIED counterexample=\"{result['counterexample']}\" first_failing_seed={first_failing_seed}")