# auto-injected by SEC sandbox
import itertools
import collections
import json
import sys
import os
import time
import re
from collections import defaultdict, Counter, deque
from itertools import product, combinations, permutations, chain
from fractions import Fraction
from typing import List, Dict, Tuple, Set, Optional, Any, Iterable, Callable
# end SEC prelude

import random
import math

def run_trial(seed: int) -> dict:
    random.seed(seed)
    n = random.randint(5, 40)
    instances_tested = 30
    total_rank = 0
    conjecture_holds = True
    counterexample = ""

    for _ in range(instances_tested):
        # Generate a random Boolean function f with n inputs
        f = [random.choice([0, 1]) for _ in range(2**n)]

        # Calculate the Fourier coefficients of f
        fourier_coeffs = []
        for k in range(2**n):
            sum_val = 0
            for x in range(2**n):
                sum_val += (-1)**sum((x >> i) & 1 for i in range(n)) * f[x]
            fourier_coeffs.append(sum_val / (2**n))

        # Calculate the algebraic K-theory rank of the free abelian group generated by non-zero Fourier coefficients
        non_zero_coeffs = [c for c in fourier_coeffs if c != 0]
        rank = len(non_zero_coeffs)

        total_rank += rank

        # Check if the inequality κ_f ≤ c·log(n) holds
        if rank > math.log(n, 2):
            conjecture_holds = False
            counterexample = f"n={n}, rank={rank}, log(n)={math.log(n, 2)}"

    metric_value = total_rank / instances_tested
    return {
        "metric_name": "Algebraic K-theory Rank",
        "metric_value": metric_value,
        "instances_tested": instances_tested,
        "conjecture_holds": conjecture_holds,
        "counterexample": counterexample
    }

if __name__ == "__main__":
    import sys
    seeds = [int(s) for s in sys.argv[1:]] or [2**i - 1 for i in range(5, 35)]
    
    results = []
    for seed in seeds:
        result = run_trial(seed)
        print(f"TRIAL: {result}")
        results.append(result)

    mean_rank = sum(r["metric_value"] for r in results) / len(results)
    std_rank = math.sqrt(sum((r["metric_value"] - mean_rank)**2 for r in results) / len(results))
    support_fraction = sum(1 for r in results if r["conjecture_holds"]) / len(results)

    if all(r["conjecture_holds"] for r in results):
        print(f"RESULT: SUPPORTED mean={mean_rank} std={std_rank} support_fraction={support_fraction}")
    elif support_fraction >= 0.8:
        print(f"RESULT: SUPPORTED mean={mean_rank} std={std_rank} support_fraction={support_fraction}")
    else:
        first_failing_seed = next(r["seed"] for r in results if not r["conjecture_holds"])
        print(f"RESULT: FALSIFIED counterexample=\"{result['counterexample']}\" first_failing_seed={first_failing_seed}")