# auto-injected by SEC sandbox
import itertools
import collections
import json
import sys
import os
import time
import re
from collections import defaultdict, Counter, deque
from itertools import product, combinations, permutations, chain
from fractions import Fraction
from typing import List, Dict, Tuple, Set, Optional, Any, Iterable, Callable
# end SEC prelude

import random
import math

def run_trial(seed: int) -> dict:
    random.seed(seed)
    
    # Generate an instance φ with n variables (n ≤ 40)
    n = random.randint(5, 40)
    φ = [random.randint(1, 2*n) for _ in range(n)]
    
    # Associate the ring R(φ) with each instance φ
    # For simplicity, we'll use a polynomial ring generated by φ
    R_φ = φ
    
    # Compute the Hodge-Tate degeneration of R(φ)
    # This is a placeholder function. In practice, this would involve more complex algebraic computations.
    def hodge_tate_deg(R):
        # Placeholder: Assume the degree is simply the sum of coefficients
        return sum(abs(x) for x in R)
    
    deg_R_φ = hodge_tate_deg(R_φ)
    
    # Determine the rank of the communication protocol φ
    rank_φ = len(φ)
    
    # Correlate the minimal degree of the Hodge-Tate degeneration with the rank
    if deg_R_φ == 0:
        return {
            "metric_name": "Hodge-Tate Degree",
            "metric_value": None,
            "instances_tested": 1,
            "n_max": n,
            "conjecture_holds": False,
            "counterexample": "Degeneration is zero, which is not within a factor of 2 from rank."
        }
    
    # Check if the conjecture holds
    if abs(deg_R_φ - rank_φ) > 0.5 * rank_φ:
        return {
            "metric_name": "Hodge-Tate Degree",
            "metric_value": deg_R_φ,
            "instances_tested": 1,
            "n_max": n,
            "conjecture_holds": False,
            "counterexample": f"Degeneration {deg_R_φ} is not within a factor of 2 from rank {rank_φ}."
        }
    
    return {
        "metric_name": "Hodge-Tate Degree",
        "metric_value": deg_R_φ,
        "instances_tested": 1,
        "n_max": n,
        "conjecture_holds": True,
        "counterexample": ""
    }

if __name__ == "__main__":
    seeds = [int(x) for x in sys.argv[1:]] if len(sys.argv) > 1 else [random.getrandbits(32) for _ in range(30)]
    
    results = []
    for seed in seeds:
        trial_result = run_trial(seed)
        print(f"TRIAL: {trial_result}")
        results.append(trial_result)
    
    # Compute mean/std of metric_value, fraction of seeds where conjecture_holds
    total_metric_value = sum(result["metric_value"] for result in results if result["metric_value"] is not None)
    total_instances_tested = sum(result["instances_tested"] for result in results)
    mean_metric_value = total_metric_value / total_instances_tested
    std_metric_value = math.sqrt(sum((result["metric_value"] - mean_metric_value) ** 2 for result in results if result["metric_value"] is not None)) / total_instances_tested
    support_fraction = sum(1 for result in results if result["conjecture_holds"]) / len(results)
    
    # Determine the final result
    if all(result["conjecture_holds"] for result in results):
        print(f"RESULT: SUPPORTED mean={mean_metric_value} std={std_metric_value} support_fraction={support_fraction}")
    elif any(not result["conjecture_holds"] for result in results):
        first_failing_seed = next(seed for seed, result in zip(seeds, results) if not result["conjecture_holds"])
        counterexample = next(result["counterexample"] for result in results if not result["conjecture_holds"])
        print(f"RESULT: FALSIFIED counterexample=\"{counterexample}\" first_failing_seed={first_failing_seed}")
    else:
        print("RESULT: INCONCLUSIVE mapping_undefined")