# auto-injected by SEC sandbox
import itertools
import collections
import json
import sys
import os
import time
import re
from collections import defaultdict, Counter, deque
from itertools import product, combinations, permutations, chain
from fractions import Fraction
from typing import List, Dict, Tuple, Set, Optional, Any, Iterable, Callable
# end SEC prelude

import random
import math

def gcd(a, b):
    while b:
        a, b = b, a % b
    return a

def lcm(a, b):
    return abs(a * b) // gcd(a, b)

def matrix_multiply(A, B):
    m, n = len(A), len(B[0])
    p = len(B)
    result = [[0] * n for _ in range(m)]
    for i in range(m):
        for j in range(n):
            for k in range(p):
                result[i][j] += A[i][k] * B[k][j]
    return result

def matrix_power(A, n):
    if n == 1:
        return A
    elif n % 2 == 0:
        half = matrix_power(A, n // 2)
        return matrix_multiply(half, half)
    else:
        return matrix_multiply(A, matrix_power(A, n - 1))

def determinant(matrix):
    if len(matrix) == 1 and len(matrix[0]) == 1:
        return matrix[0][0]
    det = 0
    for i in range(len(matrix)):
        submatrix = [row[:i] + row[i+1:] for row in matrix[1:]]
        sign = (-1) ** i
        det += sign * matrix[0][i] * determinant(submatrix)
    return det

def is_invertible(matrix):
    return determinant(matrix) != 0

def gaussian_elimination(A, b):
    n = len(A)
    Augmented_matrix = [A[i] + [b[i]] for i in range(n)]
    for i in range(n):
        max_row = max(range(i, n), key=lambda r: abs(Augmented_matrix[r][i]))
        Augmented_matrix[i], Augmented_matrix[max_row] = Augmented_matrix[max_row], Augmented_matrix[i]
        factor = Augmented_matrix[i][i]
        for j in range(i, n + 1):
            Augmented_matrix[i][j] /= factor
        for k in range(n):
            if k != i:
                factor = Augmented_matrix[k][i]
                for j in range(i, n + 1):
                    Augmented_matrix[k][j] -= factor * Augmented_matrix[i][j]
    return [row[-1] for row in Augmented_matrix]

def run_trial(seed: int) -> dict:
    random.seed(seed)
    n = random.choice([5, 10, 15, 20, 30, 40])
    M = [[random.randint(0, 1) for _ in range(n)] for _ in range(n)]
    
    # Construct the noncommutative algebra generated by M's entries
    # This is a simplified version and does not fully capture the complexity of the problem
    A = [[M[i][j] * M[k][l] - M[k][j] * M[i][l] for l in range(n)] for k in range(n) for j in range(n)]
    
    # Compute the quantum dimension using the Gelfand-Kirillov dimension
    # This is a simplified version and does not fully capture the complexity of the problem
    det = determinant(A)
    if det == 0:
        return {
            "metric_name": "quantum_dimension",
            "metric_value": float('inf'),
            "instances_tested": 1,
            "conjecture_holds": False,
            "counterexample": "mapping_undefined"
        }
    
    # The quantum dimension is the logarithm of the determinant
    quantum_dimension = math.log(det)
    
    return {
        "metric_name": "quantum_dimension",
        "metric_value": quantum_dimension,
        "instances_tested": 1,
        "conjecture_holds": quantum_dimension >= n,
        "counterexample": "" if quantum_dimension >= n else f"n={n}, quantum_dimension={quantum_dimension}"
    }

if __name__ == "__main__":
    import sys
    seeds = [int(s) for s in sys.argv[1:]] or list(range(2, 30))  # Default to first 30 primes if no seeds provided
    
    results = []
    for seed in seeds:
        result = run_trial(seed)
        print(f"TRIAL: {result}")
        results.append(result)
    
    mean_metric_value = sum(r["metric_value"] for r in results) / len(results)
    std_metric_value = math.sqrt(sum((r["metric_value"] - mean_metric_value) ** 2 for r in results) / len(results))
    support_fraction = sum(1 for r in results if r["conjecture_holds"]) / len(results)
    
    if all(r["conjecture_holds"] for r in results):
        print(f"RESULT: SUPPORTED mean={mean_metric_value} std={std_metric_value} support_fraction={support_fraction}")
    elif sum(1 for r in results if not r["conjecture_holds"]) / len(results) <= 0.2:
        print(f"RESULT: SUPPORTED mean={mean_metric_value} std={std_metric_value} support_fraction={support_fraction}")
    else:
        first_failing_seed = next(r["seed"] for r in results if not r["conjecture_holds"])
        print(f"RESULT: FALSIFIED counterexample=\"{results[0]['counterexample']}\" first_failing_seed={first_failing_seed}")