# auto-injected by SEC sandbox
import itertools
import collections
import json
import sys
import os
import time
import re
from collections import defaultdict, Counter, deque
from itertools import product, combinations, permutations, chain
from fractions import Fraction
from typing import List, Dict, Tuple, Set, Optional, Any, Iterable, Callable
# end SEC prelude

import random
import math

def gcd(a, b):
    while b:
        a, b = b, a % b
    return a

def lcm(a, b):
    return abs(a * b) // gcd(a, b)

def extended_gcd(a, b):
    if a == 0:
        return b, 0, 1
    gcd, x1, y1 = extended_gcd(b % a, a)
    x = y1 - (b // a) * x1
    y = x1
    return gcd, x, y

def mod_inverse(a, m):
    gcd, x, _ = extended_gcd(a, m)
    if gcd != 1:
        raise ValueError("Modular inverse does not exist")
    return x % m

def matrix_multiply(A, B):
    n = len(A)
    C = [[0] * n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            for k in range(n):
                C[i][j] += A[i][k] * B[k][j]
    return C

def gaussian_elimination(A, b):
    n = len(A)
    for i in range(n):
        max_row = i
        for j in range(i+1, n):
            if abs(A[j][i]) > abs(A[max_row][i]):
                max_row = j
        A[i], A[max_row] = A[max_row], A[i]
        b[i], b[max_row] = b[max_row], b[i]
        pivot = A[i][i]
        for j in range(i, n):
            A[i][j] /= pivot
        b[i] /= pivot
        for j in range(n):
            if j != i:
                factor = A[j][i]
                for k in range(i, n):
                    A[j][k] -= factor * A[i][k]
                b[j] -= factor * b[i]
    return [b[i] for i in range(n)]

def tseitin_formula(phi):
    literals = set()
    clauses = []
    def literal(x):
        if x not in literals:
            literals.add(x)
            literals.add(-x)
        return x
    def negated_literal(x):
        return -literal(x)
    def clause(*literals):
        clauses.append(literals)
    def or_clause(*literals):
        for l in literals:
            clause(negated_literal(l))
        clause(*literals)
    def and_clause(*literals):
        for l in literals:
            or_clause(negated_literal(l))
    def implies(p, q):
        or_clause(negated_literal(p), q)
    def iff(p, q):
        and_clause(implies(p, q), implies(q, p))
    def not_implies(p, q):
        or_clause(p, negated_literal(q))
    def xor(p, q):
        or_clause(p, q)
        not_implies(p, q)
    def nand(p, q):
        or_clause(negated_literal(p), negated_literal(q))
        implies(p, q)
    def nor(p, q):
        or_clause(negated_literal(p), negated_literal(q))
        implies(q, p)
    def xor3(p, q, r):
        or_clause(p, q)
        not_implies(p, q)
        or_clause(p, r)
        not_implies(p, r)
        or_clause(q, r)
        not_implies(q, r)
    def nand3(p, q, r):
        or_clause(negated_literal(p), negated_literal(q))
        implies(p, q)
        or_clause(negated_literal(p), negated_literal(r))
        implies(p, r)
        or_clause(negated_literal(q), negated_literal(r))
        implies(q, r)
    def nor3(p, q, r):
        or_clause(negated_literal(p), negated_literal(q))
        implies(q, p)
        or_clause(negated_literal(p), negated_literal(r))
        implies(r, p)
        or_clause(negated_literal(q), negated_literal(r))
        implies(r, q)
    def xor4(p, q, r, s):
        or_clause(p, q)
        not_implies(p, q)
        or_clause(p, r)
        not_implies(p, r)
        or_clause(p, s)
        not_implies(p, s)
        or_clause(q, r)
        not_implies(q, r)
        or_clause(q, s)
        not_implies(q, s)
        or_clause(r, s)
        not_implies(r, s)
    def nand4(p, q, r, s):
        or_clause(negated_literal(p), negated_literal(q))
        implies(p, q)
        or_clause(negated_literal(p), negated_literal(r))
        implies(p, r)
        or_clause(negated_literal(p), negated_literal(s))
        implies(p, s)
        or_clause(negated_literal(q), negated_literal(r))
        implies(q, r)
        or_clause(negated_literal(q), negated_literal(s))
        implies(q, s)
        or_clause(negated_literal(r), negated_literal(s))
        implies(r, s)
    def nor4(p, q, r, s):
        or_clause(negated_literal(p), negated_literal(q))
        implies(q, p)
        or_clause(negated_literal(p), negated_literal(r))
        implies(r, p)
        or_clause(negated_literal(p), negated_literal(s))
        implies(s, p)
        or_clause(negated_literal(q), negated_literal(r))
        implies(r, q)
        or_clause(negated_literal(q), negated_literal(s))
        implies(s, q)
        or_clause(negated_literal(r), negated_literal(s))
        implies(s, r)
    def xor5(p, q, r, s, t):
        or_clause(p, q)
        not_implies(p, q)
        or_clause(p, r)
        not_implies(p, r)
        or_clause(p, s)
        not_implies(p, s)
        or_clause(p, t)
        not_implies(p, t)
        or_clause(q, r)
        not_implies(q, r)
        or_clause(q, s)
        not_implies(q, s)
        or_clause(q, t)
        not_implies(q, t)
        or_clause(r, s)
        not_implies(r, s)
        or_clause(r, t)
        not_implies(r, t)
        or_clause(s, t)
        not_implies(s, t)
    def nand5(p, q, r, s, t):
        or_clause(negated_literal(p), negated_literal(q))
        implies(p, q)
        or_clause(negated_literal(p), negated_literal(r))
        implies(p, r)
        or_clause(negated_literal(p), negated_literal(s))
        implies(p, s)
        or_clause(negated_literal(p), negated_literal(t))
        implies(p, t)
        or_clause(negated_literal(q), negated_literal(r))
        implies(q, r)
        or_clause(negated_literal(q), negated_literal(s))
        implies(q, s)
        or_clause(negated_literal(q), negated_literal(t))
        implies(q, t)
        or_clause(negated_literal(r), negated_literal(s))
        implies(r, s)
        or_clause(negated_literal(r), negated_literal(t))
        implies(r, t)
        or_clause(negated_literal(s), negated_literal(t))
        implies(s, t)
    def nor5(p, q, r, s, t):
        or_clause(negated_literal(p), negated_literal(q))
        implies(q, p)
        or_clause(negated_literal(p), negated_literal(r))
        implies(r, p)
        or_clause(negated_literal(p), negated_literal(s))
        implies(s, p)
        or_clause(negated_literal(p), negated_literal(t))
        implies(t, p)
        or_clause(negated_literal(q), negated_literal(r))
        implies(r, q)
        or_clause(negated_literal(q), negated_literal(s))
        implies(s, q)
        or_clause(negated_literal(q), negated_literal(t))
        implies(t, q)
        or_clause(negated_literal(r), negated_literal(s))
        implies(s, r)
        or_clause(negated_literal(r), negated_literal(t))
        implies(t, r)
        or_clause(negated_literal(s), negated_literal(t))
        implies(t, s)
    def xor6(p, q, r, s, t, u):
        or_clause(p, q)
        not_implies(p, q)
        or_clause(p, r)
        not_implies(p, r)
        or_clause(p, s)
        not_implies(p, s)
        or_clause(p, t)
        not_implies(p, t)
        or_clause(p, u)
        not_implies(p, u)
        or_clause(q, r)
        not_implies(q, r)
        or_clause(q, s)
        not_implies(q, s)
        or_clause(q, t)
        not_implies(q, t)
        or_clause(q, u)
        not_implies(q, u)
        or_clause(r, s)
        not_implies(r, s)
        or_clause(r, t)
        not_implies(r, t)
        or_clause(r, u)
        not_implies(r, u)
        or_clause(s, t)
        not_implies(s, t)
        or_clause(s, u)
        not_implies(s, u)
        or_clause(t, u)
        not_implies(t, u)
    def nand6(p, q, r, s, t, u):
        or_clause(negated_literal(p), negated_literal(q))
        implies(p, q)
        or_clause(negated_literal(p), negated_literal(r))
        implies(p, r)
        or_clause(negated_literal(p), negated_literal(s))
        implies(p, s)
        or_clause(negated_literal(p), negated_literal(t))
        implies(p, t)
        or_clause(negated_literal(p), negated_literal(u))
        implies(p, u)
        or_clause(negated_literal(q), negated_literal(r))
        implies(q, r)
        or_clause(negated_literal(q), negated_literal(s))
        implies(q, s)
        or_clause(negated_literal(q), negated_literal(t))
        implies(q, t)
        or_clause(negated_literal(q), negated_literal(u))
        implies(q, u)
        or_clause(negated_literal(r), negated_literal(s))
        implies(r, s)
        or_clause(negated_literal(r), negated_literal(t))
        implies(r, t)
        or_clause(negated_literal(r), negated_literal(u))
        implies(r, u)
        or_clause(negated_literal(s), negated_literal(t))
        implies(s, t)
        or_clause(negated_literal(s), negated_literal(u))
        implies(s, u)
        or_clause(negated_literal(t), negated_literal(u))
        implies(t, u)
    def nor6(p, q, r, s, t, u):
        or_clause(negated_literal(p), negated_literal(q))
        implies(q, p)
        or_clause(negated_literal(p), negated_literal(r))
        implies(r, p)
        or_clause(negated_literal(p), negated_literal(s))
        implies(s, p)
        or_clause(negated_literal(p), negated_literal(t))
        implies(t, p)
        or_clause(negated_literal(p), negated_literal(u))
        implies(u, p)
        or_clause(negated_literal(q), negated_literal(r))
        implies(r, q)
        or_clause(negated_literal(q), negated_literal(s))
        implies(s, q)
        or_clause(negated_literal(q), negated_literal(t))
        implies(t, q)
        or_clause(negated_literal(q), negated_literal(u))
        implies(u, q)
        or_clause(negated_literal(r), negated_literal(s))
        implies(s, r)
        or_clause(negated_literal(r), negated_literal(t))
        implies(t, r)
        or_clause(negated_literal(r), negated_literal(u))
        implies(u, r)
        or_clause(negated_literal(s), negated_literal(t))
        implies(t, s)
        or_clause(negated_literal(s), negated_literal(u))
        implies(u, s)
        or_clause(negated_literal(t), negated_literal(u))
        implies(u, t)
    def xor7(p, q, r, s, t, u, v):
        or_clause(p, q)
        not_implies(p, q)
        or_clause(p, r)
        not_implies(p, r)
        or_clause(p, s)
        not_implies(p, s)
        or_clause(p, t)
        not_implies(p, t)
        or_clause(p, u)
        not_implies(p, u)
        or_clause(p, v)
        not_implies(p, v)
        or_clause(q, r)
        not_implies(q, r)
        or_clause(q, s)
        not_implies(q, s)
        or_clause(q, t)
        not_implies(q, t)
        or_clause(q, u)
        not_implies(q, u)
        or_clause(q, v)
        not_implies(q, v)
        or_clause(r, s)
        not_implies(r, s)
        or_clause(r, t)
        not_implies(r, t)
        or_clause(r, u)
        not_implies(r, u)
        or_clause(r, v)
        not_implies(r, v)
        or_clause(s, t)
        not_implies(s, t)
        or_clause(s, u)
        not_implies(s, u)
        or_clause(s, v)
        not_implies(s, v)
        or_clause(t, u)
        not_implies(t, u)
        or_clause(t, v)
        not_implies(t, v)
        or_clause(u, v)
        not_implies(u, v)
    def nand7(p, q, r, s, t, u, v):
        or_clause(negated_literal(p), negated_literal(q))
        implies(p, q)
        or_clause(negated_literal(p), negated_literal(r))
        implies(p, r)
        or_clause(negated_literal(p), negated_literal(s))
        implies(p, s)
        or_clause(negated_literal(p), negated_literal(t))
        implies(p, t)
        or_clause(negated_literal(p), negated_literal(u))
        implies(p, u)
        or_clause(negated_literal(p), negated_literal(v))
        implies(p, v)
        or_clause(negated_literal(q), negated_literal(r))
        implies(q, r)
        or_clause(negated_literal(q), negated_literal(s))
        implies(q, s)
        or_clause(negated_literal(q), negated_literal(t))
        implies(q, t)
        or_clause(negated_literal(q), negated_literal(u))
        implies(q, u)
        or_clause(negated_literal(q), negated_literal(v))
        implies(q, v)
        or_clause(negated_literal(r), negated_literal(s))
        implies(r, s)
        or_clause(negated_literal(r), negated_literal(t))
        implies(r, t)
        or_clause(negated_literal(r), negated_literal(u))
        implies(r, u)
        or_clause(negated_literal(r), negated_literal(v))
        implies(r, v)
        or_clause(negated_literal(s), negated_literal(t))
        implies(s, t)
        or_clause(negated_literal(s), negated_literal(u))
        implies(s, u)
        or_clause(negated_literal(s), negated_literal(v))
        implies(s, v)
        or_clause(negated_literal(t), negated_literal(u))
        implies(t, u)
        or_clause(negated_literal(t), negated_literal(v))
        implies(t, v)
        or_clause(negated_literal(u), negated_literal(v))
        implies(u, v)
    def nor7(p, q, r, s, t, u, v):
        or_clause(negated_literal(p), negated_literal(q))
        implies(q, p)
        or_clause(negated_literal(p), negated_literal(r))
        implies(r, p)
        or_clause(negated_literal(p), negated_literal(s))
        implies(s, p)
        or_clause(negated_literal(p), negated_literal(t))
        implies(t, p)
        or_clause(negated_literal(p), negated_literal(u))
        implies(u, p)
        or_clause(negated_literal(p), negated_literal(v))
        implies(v, p)
        or_clause(negated_literal(q), negated_literal(r))
        implies(r, q)
        or_clause(negated_literal(q), negated_literal(s))
        implies(s, q)
        or_clause(negated_literal(q), negated_literal(t))
        implies(t, q)
        or_clause(negated_literal(q), negated_literal(u))
        implies(u, q)
        or_clause(negated_literal(q), negated_literal(v))
        implies(v, q)
        or_clause(negated_literal(r), negated_literal(s))
        implies(s, r)
        or_clause(negated_literal(r), negated_literal(t))
        implies(t, r)
        or_clause(negated_literal(r), negated_literal(u))
        implies(u, r)
        or_clause(negated_literal(r), negated_literal(v))
        implies(v, r)
        or_clause(negated_literal(s), negated_literal(t))
        implies(t, s)
        or_clause(negated_literal(s), negated_literal(u))
        implies(u, s)
        or_clause(negated_literal(s), negated_literal(v))
        implies(v, s)
        or_clause(negated_literal(t), negated_literal(u))
        implies(u, t)
        or_clause(negated_literal(t), negated_literal(v))
        implies(v, t)
        or_clause(negated_literal(u), negated_literal(v))
        implies(v, u)
    def xor8(p, q, r, s, t, u, v, w):
        or_clause(p, q)
        not_implies(p, q)
        or_clause(p, r)
        not_implies(p, r)
        or_clause(p, s)
        not_implies(p, s)
        or_clause(p, t)
        not_implies(p, t)
        or_clause(p, u)
        not_implies(p, u)
        or_clause(p, v)
        not_implies(p, v)
        or_clause(p, w)
        not_implies(p, w)
        or_clause(q, r)
        not_implies(q, r)
        or_clause(q, s)
        not_implies(q, s)
        or_clause(q, t)
        not_implies(q, t)
        or_clause(q, u)
        not_implies(q, u)
        or_clause(q, v)
        not_implies(q, v)
        or_clause(q, w)
        not_implies(q, w)
        or_clause(r, s)
        not_implies(r, s)
        or_clause(r, t)
        not_implies(r, t)
        or_clause(r, u)
        not_implies(r, u)
        or_clause(r, v)
        not_implies(r, v)
        or_clause(r, w)
        not_implies(r, w)
        or_clause(s, t)
        not_implies(s, t)
        or_clause(s, u)
        not_implies(s, u)
        or_clause(s, v)
        not_implies(s, v)
        or_clause(s, w)
        not_implies(s, w)
        or_clause(t, u)
        not_implies(t, u)
        or_clause(t, v)
        not_implies(t, v)
        or_clause(t, w)
        not_implies(t, w)
        or_clause(u, v)
        not_implies(u, v)
        or_clause(u, w)
        not_implies(u, w)
        or_clause(v, w)
        not_implies(v, w)
    def nand8(p, q, r, s, t, u, v, w):
        or_clause(negated_literal(p), negated_literal(q))
        implies(p, q)
        or_clause(negated_literal(p), negated_literal(r))
        implies(p, r)
        or_clause(negated_literal(p), negated_literal(s))
        implies(p, s)
        or_clause(negated_literal(p), negated_literal(t))
        implies(p, t)