# auto-injected by SEC sandbox
import itertools
import collections
import json
import sys
import os
import time
import re
from collections import defaultdict, Counter, deque
from itertools import product, combinations, permutations, chain
from fractions import Fraction
from typing import List, Dict, Tuple, Set, Optional, Any, Iterable, Callable
# end SEC prelude

import random
import math

def gcd(a, b):
    while b:
        a, b = b, a % b
    return a

def lcm(a, b):
    return abs(a*b) // gcd(a, b)

def matrix_multiply(A, B):
    n = len(A)
    C = [[0]*n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            for k in range(n):
                C[i][j] += A[i][k] * B[k][j]
    return C

def matrix_power(M, n):
    result = [[int(i==j) for j in range(len(M))] for i in range(len(M))]
    while n > 0:
        if n % 2 == 1:
            result = matrix_multiply(result, M)
        M = matrix_multiply(M, M)
        n //= 2
    return result

def gaussian_elimination(A):
    n = len(A)
    for i in range(n):
        max_row = i
        for j in range(i+1, n):
            if abs(A[j][i]) > abs(A[max_row][i]):
                max_row = j
        A[i], A[max_row] = A[max_row], A[i]
        if A[i][i] == 0:
            return None  # Singular matrix
        for j in range(i+1, n):
            factor = A[j][i] / A[i][i]
            for k in range(n):
                A[j][k] -= factor * A[i][k]
    return A

def determinant(A):
    n = len(A)
    if n == 2:
        return A[0][0]*A[1][1] - A[0][1]*A[1][0]
    det = 0
    for j in range(n):
        submatrix = [row[:j] + row[j+1:] for row in A[1:]]
        det += (-1)**j * A[0][j] * determinant(submatrix)
    return det

def run_trial(seed: int) -> dict:
    random.seed(seed)
    n = random.randint(5, 40)
    ACC0_size = random.randint(1, n)
    
    # Generate a random polynomial function f
    coefficients = [random.randint(-n, n) for _ in range(n+1)]
    def f(x):
        return sum(c * x**i for i, c in enumerate(coefficients))
    
    # Compute the semigroup generated by f
    semigroup = set()
    for i in range(100):  # Sample enough points to ensure coverage
        x = random.randint(-n, n)
        value = f(x)
        if value > 0:
            semigroup.add(value)
    
    # Compute the minimal Ehrhart quotient ρ(f)
    min_quotient = float('inf')
    for delta in [1e-6 * i for i in range(1, 100)]:
        count = sum(1 for value in semigroup if delta < value <= 1 + delta)
        if count > 0:
            quotient = len(semigroup) / count
            min_quotient = min(min_quotient, quotient)
    
    # Check the conjecture
    if ACC0_size <= n:
        expected_bound = math.log(n)**2
        holds = expected_bound - 1 <= min_quotient <= expected_bound + 1
    else:
        holds = min_quotient <= n
    
    return {
        "metric_name": "minimal_Ehrhart_quotient",
        "metric_value": min_quotient,
        "instances_tested": len(semigroup),
        "conjecture_holds": holds,
        "counterexample": "" if holds else f"ACC0_size={ACC0_size}, n={n}"
    }

if __name__ == "__main__":
    import sys
    seeds = [int(s) for s in sys.argv[1:]] or list(range(2, 37))  # Default to first 30 primes if no seeds provided
    
    results = []
    for seed in seeds:
        trial_result = run_trial(seed)
        print(f"TRIAL: {trial_result}")
        results.append(trial_result)
    
    mean_value = sum(result["metric_value"] for result in results) / len(results)
    std_value = math.sqrt(sum((result["metric_value"] - mean_value)**2 for result in results) / len(results))
    support_fraction = sum(1 for result in results if result["conjecture_holds"]) / len(results)
    
    if all(result["conjecture_holds"] for result in results):
        print(f"RESULT: SUPPORTED mean={mean_value} std={std_value} support_fraction={support_fraction}")
    elif support_fraction >= 0.8:
        print(f"RESULT: SUPPORTED mean={mean_value} std={std_value} support_fraction={support_fraction}")
    else:
        first_failing_seed = next(seed for seed, result in zip(seeds, results) if not result["conjecture_holds"])
        print(f"RESULT: FALSIFIED counterexample=\"{result['counterexample']}\" first_failing_seed={first_failing_seed}")