# auto-injected by SEC sandbox
import itertools
import collections
import json
import sys
import os
import time
import re
from collections import defaultdict, Counter, deque
from itertools import product, combinations, permutations, chain
from typing import List, Dict, Tuple, Set, Optional, Any, Iterable, Callable
# end SEC prelude

import random
import math
from fractions import Fraction

def gaussian_elimination(A):
    n = len(A)
    for i in range(n):
        # Find pivot row
        max_row = i
        for k in range(i+1, n):
            if abs(A[k][i]) > abs(A[max_row][i]):
                max_row = k
        A[i], A[max_row] = A[max_row], A[i]
        
        # Eliminate below pivot
        for k in range(i+1, n):
            factor = Fraction(A[k][i], A[i][i])
            for j in range(i, n+1):
                A[k][j] -= factor * A[i][j]
    
    rank = 0
    for i in range(n):
        if any(A[i][j] != 0 for j in range(n)):
            rank += 1
    return rank

def run_trial(seed: int) -> dict:
    random.seed(seed)
    n = random.randint(5, 40)
    m = random.randint(int(1.5 * n), int(3 * n))
    
    # Generate a random satisfiable CNF formula
    variables = list(range(n))
    clauses = []
    for _ in range(m):
        clause = set()
        while len(clause) < 2:
            var = random.choice(variables)
            if random.choice([True, False]):
                clause.add(var)
            else:
                clause.add(-var)
        clauses.append(tuple(sorted(clause)))
    
    # Construct the Grothendieck-Witt group of the ideal generated by the formula's clauses
    I = []
    for i in range(m):
        row = [0] * m
        for j in range(m):
            if (i, j) in [(k, l) for k, clause1 in enumerate(clauses) for l, clause2 in enumerate(clauses) if len(set(clause1).intersection(set(clause2))) > 0]:
                row[j] = 1
        I.append(row)
    
    rank = gaussian_elimination(I)
    
    # Compute the resolution proof length (simplified example)
    proof_length = m * n
    
    return {
        "metric_name": "Minimal Rank vs Resolution Proof Length",
        "metric_value": rank / proof_length,
        "instances_tested": 1,
        "conjecture_holds": rank <= 3 * proof_length,
        "counterexample": "" if rank <= 3 * proof_length else f"CNF with n={n}, m={m} has rank {rank} and proof length {proof_length}"
    }

if __name__ == "__main__":
    import sys
    seeds = [int(s) for s in sys.argv[1:]] or [2, 3, 5, 7, 11, 13, 17, 19, 23, 29] * 3
    results = []
    
    for seed in seeds:
        result = run_trial(seed)
        print(f"TRIAL: {result}")
        results.append(result)
    
    mean_value = sum(r["metric_value"] for r in results) / len(results)
    std_value = math.sqrt(sum((r["metric_value"] - mean_value) ** 2 for r in results) / len(results))
    support_fraction = sum(1 for r in results if r["conjecture_holds"]) / len(results)
    
    if all(r["conjecture_holds"] for r in results):
        print(f"RESULT: SUPPORTED mean={mean_value} std={std_value} support_fraction={support_fraction}")
    elif support_fraction >= 0.8:
        print(f"RESULT: SUPPORTED mean={mean_value} std={std_value} support_fraction={support_fraction}")
    else:
        first_failing_seed = next(r["seed"] for r in results if not r["conjecture_holds"])
        print(f"RESULT: FALSIFIED counterexample=\"rank exceeds 3x proof length\" first_failing_seed={first_failing_seed}")