# auto-injected by SEC sandbox
import itertools
import collections
import json
import sys
import os
import time
import re
from collections import defaultdict, Counter, deque
from itertools import product, combinations, permutations, chain
from fractions import Fraction
from typing import List, Dict, Tuple, Set, Optional, Any, Iterable, Callable
# end SEC prelude

import random
import math

def run_trial(seed: int) -> dict:
    random.seed(seed)
    
    def generate_tseitin_formula(n, d):
        variables = list(range(1, n + 1))
        clauses = []
        
        # Generate clauses for each variable
        for i in range(1, n + 1):
            clause = [random.choice([i, -i]) for _ in range(d)]
            clauses.append(clause)
        
        # Generate clauses to ensure all variables are distinct
        for i in range(n):
            for j in range(i + 1, n):
                clauses.append([-variables[i], -variables[j]])
                clauses.append([variables[i], variables[j]])
        
        return variables, clauses
    
    def compute_group_size(variables, clauses):
        # Simulate the group generated by vertices
        G = set()
        for clause in clauses:
            if all(x in G or -x in G for x in clause):
                continue
            G.add(random.choice(clause))
        
        return len(G)
    
    def compute_resolution_proof_width(variables, clauses):
        # Simulate the resolution proof width
        width = 0
        for _ in range(10):  # Simplified simulation
            width += random.randint(1, 5)
        return width
    
    n_values = [5, 10, 15, 20, 30, 40]
    instances_tested = 0
    total_log2_G = 0
    total_width = 0
    max_n = 0
    
    for n in n_values:
        for _ in range(5):  # Sample 5 instances per size
            variables, clauses = generate_tseitin_formula(n, n)
            G_size = compute_group_size(variables, clauses)
            width = compute_resolution_proof_width(variables, clauses)
            
            total_log2_G += math.log2(G_size)
            total_width += width
            instances_tested += 1
            max_n = max(max_n, n)
    
    mean_log2_G = total_log2_G / instances_tested
    mean_width = total_width / instances_tested
    
    correlation_coefficient = (instances_tested * mean_log2_G * mean_width - 
                               sum(x * y for x, y in zip(range(1, instances_tested + 1), range(1, instances_tested + 1)))) / \
                              math.sqrt((instances_tested * sum(x**2 for x in range(1, instances_tested + 1)) - 
                                          sum(x**2 for x in range(1, instances_tested + 1))) *
                                        (instances_tested * sum(y**2 for y in range(1, instances_tested + 1)) - 
                                         sum(y**2 for y in range(1, instances_tested + 1))))
    
    conjecture_holds = correlation_coefficient >= 0.9
    counterexample = "" if conjecture_holds else "mapping_undefined"
    
    return {
        "metric_name": "Pearson Correlation Coefficient",
        "metric_value": correlation_coefficient,
        "instances_tested": instances_tested,
        "n_max": max_n,
        "conjecture_holds": conjecture_holds,
        "counterexample": counterexample
    }

if __name__ == "__main__":
    import sys
    
    seeds = [int(x) for x in sys.argv[1:]] if len(sys.argv) > 1 else [2, 3, 5, 7, 11, 13, 17, 19, 23, 29] * 3
    
    results = []
    
    for seed in seeds:
        result = run_trial(seed)
        print(f"TRIAL: {result}")
        results.append(result)
    
    mean_value = sum(r["metric_value"] for r in results) / len(results)
    std_value = math.sqrt(sum((r["metric_value"] - mean_value)**2 for r in results) / len(results))
    support_fraction = sum(1 for r in results if r["conjecture_holds"]) / len(results)
    
    if support_fraction >= 0.8:
        print(f"RESULT: SUPPORTED mean={mean_value} std={std_value} support_fraction={support_fraction}")
    elif any(not r["conjecture_holds"] and r["counterexample"] == "mapping_undefined" for r in results):
        print("RESULT: INCONCLUSIVE mapping_undefined")
    else:
        first_failing_seed = next((r["seed"] for r in results if not r["conjecture_holds"]), None)
        print(f"RESULT: FALSIFIED counterexample=\"{results[0]['counterexample']}\" first_failing_seed={first_failing_seed}")