# auto-injected by SEC sandbox
import itertools
import collections
import json
import os
import time
import re
from collections import defaultdict, Counter, deque
from itertools import product, combinations, permutations, chain
from typing import List, Dict, Tuple, Set, Optional, Any, Iterable, Callable
# end SEC prelude

import random
import math
from fractions import Fraction
import sys

def run_trial(seed: int) -> dict:
    random.seed(seed)
    
    def generate_polynomial(n, w):
        # Generate a random polynomial over GF(2)
        poly = [random.choice([0, 1]) for _ in range(n)]
        return poly
    
    def partial_derivatives(poly_str, vars, x_values):
        # Compute partial derivatives
        partials = []
        for var in vars:
            partial = ""
            for i, coeff in enumerate(poly_str.split()):
                if var in coeff:
                    power = int(coeff[coeff.index(var) + 1:])
                    if power > 0:
                        new_coeff = str((power * int(coeff[:coeff.index(var)])) % 2)
                        new_var = f"{var}^{power-1}"
                        partial += f"{new_coeff}*{new_var} "
            partials.append(partial.strip())
        return partials
    
    def construct_ideal(partials):
        # Construct the ideal generated by partial derivatives
        I = set()
        for part in partials:
            I.update(set(part.split()))
        return I
    
    def castelnuovo_mumford_regularity(I, n):
        # Compute Castelnuovo-Mumford regularity (simplified)
        return len(I) * math.log(n, 2)
    
    n = random.randint(5, 40)
    w = random.randint(1, 10)
    poly_str = generate_polynomial(n, w)
    vars = [f"x{i}" for i in range(w)]
    x_values = [random.randint(0, 1) for _ in range(n)]
    
    partials = partial_derivatives(poly_str, vars, x_values)
    I = construct_ideal(partials)
    reg_I = castelnuovo_mumford_regularity(I, n)
    
    metric_name = "castelnuovo_mumford_regularity"
    metric_value = reg_I
    instances_tested = 1
    conjecture_holds = reg_I <= w * math.log(n, 2) + 10
    counterexample = "" if conjecture_holds else f"reg(I)={reg_I} > {w * math.log(n, 2) + 10}"
    
    return {
        "metric_name": metric_name,
        "metric_value": metric_value,
        "instances_tested": instances_tested,
        "conjecture_holds": conjecture_holds,
        "counterexample": counterexample
    }

if __name__ == "__main__":
    seeds = [int(s) for s in sys.argv[1:]] if sys.argv[1:] else list(range(2, 30))  # Default to first 29 primes
    results = []
    
    for seed in seeds:
        result = run_trial(seed)
        print(f"TRIAL: {{'seed': {seed}, ...{result}...}}")
        results.append(result)
    
    mean_value = sum(r["metric_value"] for r in results) / len(results)
    std_value = math.sqrt(sum((r["metric_value"] - mean_value) ** 2 for r in results) / len(results))
    support_fraction = sum(1 for r in results if r["conjecture_holds"]) / len(results)
    
    if support_fraction >= 0.8:
        print(f"RESULT: SUPPORTED mean={mean_value} std={std_value} support_fraction={support_fraction}")
    elif any(not r["conjecture_holds"] for r in results):
        first_failing_seed = next(s for s, r in enumerate(results) if not r["conjecture_holds"])
        print(f"RESULT: FALSIFIED counterexample=\"{results[first_failing_seed]['counterexample']}\" first_failing_seed={first_failing_seed}")
    else:
        print("RESULT: INCONCLUSIVE insufficient support")