# auto-injected by SEC sandbox
import itertools
import collections
import json
import sys
import os
import time
import re
from collections import defaultdict, Counter, deque
from itertools import product, combinations, permutations, chain
from typing import List, Dict, Tuple, Set, Optional, Any, Iterable, Callable
# end SEC prelude

import random
import math
from fractions import Fraction

def run_trial(seed: int) -> dict:
    random.seed(seed)
    
    def galois_group_order(circuit):
        n = len(circuit)
        if n == 0:
            return 1
        
        # Construct the field generated by the circuit's output
        field = {0, 1}
        for i in range(n):
            new_element = (field[0] ^ circuit[i]) % 2
            if new_element not in field:
                field.add(new_element)
        
        # The Galois group order is the size of the field
        return len(field)

    def entanglement_entropy(circuit):
        n = len(circuit)
        ones_count = circuit.count(1)
        zeros_count = n - ones_count
        if ones_count == 0 or zeros_count == 0:
            return 0
        
        p_one = Fraction(ones_count, n)
        p_zero = Fraction(zeros_count, n)
        
        entropy = -p_one * math.log2(p_one) - p_zero * math.log2(p_zero)
        return entropy

    def generate_random_circuit(n):
        return [random.randint(0, 1) for _ in range(n)]

    correlation_sum = 0
    instances_tested = 0
    n_max = 0

    for n in {5, 10, 15, 20, 30, 40}:
        if n > n_max:
            n_max = n
        
        for _ in range(5):  # At least 30 instances per seed
            circuit = generate_random_circuit(n)
            group_order = galois_group_order(circuit)
            entropy = entanglement_entropy(circuit)
            
            correlation_sum += group_order * entropy
            instances_tested += 1

    if instances_tested < 30:
        return {
            "metric_name": "correlation",
            "metric_value": None,
            "instances_tested": instances_tested,
            "n_max": n_max,
            "conjecture_holds": False,
            "counterexample": "insufficient_instances"
        }

    correlation = correlation_sum / instances_tested
    return {
        "metric_name": "correlation",
        "metric_value": correlation,
        "instances_tested": instances_tested,
        "n_max": n_max,
        "conjecture_holds": correlation >= 0.5,
        "counterexample": ""
    }

if __name__ == "__main__":
    seeds = [int(x) for x in sys.argv[1:]] or [2, 3, 5, 7, 11, 13, 17, 19, 23, 29] * 3
    results = []

    for seed in seeds:
        trial_result = run_trial(seed)
        print(f"TRIAL: {trial_result}")
        results.append(trial_result)

    mean_value = sum(result["metric_value"] for result in results if result["metric_value"] is not None) / len(results)
    support_fraction = sum(1 for result in results if result["conjecture_holds"]) / len(results)

    if all("support" in result and result["support"] for result in results):
        print(f"RESULT: SUPPORTED mean={mean_value} std=0.0 support_fraction={support_fraction}")
    elif any("counterexample" in result and result["counterexample"] for result in results):
        first_failing_seed = next(result["seed"] for result in results if "counterexample" in result)
        print(f"RESULT: FALSIFIED counterexample=\"{next(result['counterexample'] for result in results if 'counterexample' in result)}\" first_failing_seed={first_failing_seed}")
    else:
        print(f"RESULT: INCONCLUSIVE reason=insufficient_data")