# auto-injected by SEC sandbox
import itertools
import collections
import json
import sys
import os
import time
import re
from collections import defaultdict, Counter, deque
from itertools import product, combinations, permutations, chain
from fractions import Fraction
from typing import List, Dict, Tuple, Set, Optional, Any, Iterable, Callable
# end SEC prelude

import random
import math

def run_trial(seed: int) -> dict:
    random.seed(seed)
    
    def gaussian_elimination(A):
        m, n = len(A), len(A[0])
        for i in range(m):
            max_row = i
            for j in range(i+1, m):
                if abs(A[j][i]) > abs(A[max_row][i]):
                    max_row = j
            A[i], A[max_row] = A[max_row], A[i]
            factor = 1 / A[i][i]
            for j in range(n):
                A[i][j] *= factor
            for j in range(m):
                if i != j:
                    factor = A[j][i]
                    for k in range(n):
                        A[j][k] -= factor * A[i][k]
        return A

    def matrix_multiplication(A, B):
        m, n, p = len(A), len(B), len(B[0])
        C = [[0] * p for _ in range(m)]
        for i in range(m):
            for j in range(p):
                for k in range(n):
                    C[i][j] += A[i][k] * B[k][j]
        return C

    def quasi_boolean_homology(n, m):
        # Construct a random satisfiable CNF formula
        clauses = []
        variables = set()
        for _ in range(m):
            clause = [random.choice([1, -1]) * (i + 1) for i in range(random.randint(2, n))]
            clauses.append(clause)
            variables.update(abs(x) for x in clause)
        
        # Construct the Grothendieck-Witt group of the ideal generated by the formula's clauses
        A = [[0] * len(variables) for _ in range(len(variables))]
        for clause in clauses:
            for i, var1 in enumerate(variables):
                for j, var2 in enumerate(variables):
                    if abs(var1) == abs(var2):
                        A[i][j] += sum(x * y for x, y in zip(clause, clause))
        
        # Perform Gaussian elimination to find the rank of the matrix
        rank = 0
        A = gaussian_elimination(A)
        for row in A:
            if any(row):
                rank += 1
        
        return rank

    def resolution_proof_length(n, m):
        # This is a placeholder function. In practice, you would need an actual implementation of the resolution algorithm.
        # For simplicity, we assume a linear relationship between n and m for this example.
        return n + m

    n_values = [5, 10, 15, 20, 30, 40]
    results = []
    
    for n in n_values:
        m = random.randint(2 * n, 3 * n)
        rank = quasi_boolean_homology(n, m)
        proof_length = resolution_proof_length(n, m)
        
        if proof_length == 0 or rank == 0:
            continue
        
        results.append({
            "n": n,
            "m": m,
            "rank": rank,
            "proof_length": proof_length
        })
    
    if not results:
        return {
            "metric_name": "minimal_rank_over_proof_length",
            "metric_value": None,
            "instances_tested": 0,
            "conjecture_holds": False,
            "counterexample": "no_valid_instances"
        }
    
    min_ratio = min(result["rank"] / result["proof_length"] for result in results)
    max_ratio = max(result["rank"] / result["proof_length"] for result in results)
    
    return {
        "metric_name": "minimal_rank_over_proof_length",
        "metric_value": (min_ratio + max_ratio) / 2,
        "instances_tested": len(results),
        "conjecture_holds": min_ratio <= 1/3 and max_ratio <= 1/3,
        "counterexample": ""
    }

if __name__ == "__main__":
    import sys
    seeds = [int(x) for x in sys.argv[1:]] or list(range(2, 50, 2))  # Default to first 24 odd primes if no seeds provided
    
    results = []
    for seed in seeds:
        trial_result = run_trial(seed)
        print(f"TRIAL: {trial_result}")
        results.append(trial_result)
    
    mean_value = sum(result["metric_value"] for result in results) / len(results)
    std_value = math.sqrt(sum((result["metric_value"] - mean_value) ** 2 for result in results) / len(results))
    support_fraction = sum(1 for result in results if result["conjecture_holds"]) / len(results)
    
    if all(result["conjecture_holds"] for result in results):
        print(f"RESULT: SUPPORTED mean={mean_value} std={std_value} support_fraction={support_fraction}")
    elif support_fraction >= 0.8:
        print(f"RESULT: SUPPORTED mean={mean_value} std={std_value} support_fraction={support_fraction}")
    else:
        first_failing_seed = next(seed for seed, result in zip(seeds, results) if not result["conjecture_holds"])
        print(f"RESULT: FALSIFIED counterexample='minimal_rank_too_large' first_failing_seed={first_failing_seed}")