# auto-injected by SEC sandbox
import itertools
import collections
import json
import sys
import os
import time
import re
from collections import defaultdict, Counter, deque
from itertools import product, combinations, permutations, chain
from fractions import Fraction
from typing import List, Dict, Tuple, Set, Optional, Any, Iterable, Callable
# end SEC prelude

import random
import math

def run_trial(seed: int) -> dict:
    random.seed(seed)
    
    def generate_random_communication_instance(n):
        # Generate a random communication complexity instance
        A = [[random.choice([0, 1]) for _ in range(n)] for _ in range(n)]
        B = [[random.choice([0, 1]) for _ in range(n)] for _ in range(n)]
        return A, B
    
    def matrix_add(A, B):
        # Add two matrices
        return [[A[i][j] + B[i][j] for j in range(len(A[0]))] for i in range(len(A))]
    
    def matrix_sub(A, B):
        # Subtract two matrices
        return [[A[i][j] - B[i][j] for j in range(len(A[0]))] for i in range(len(A))]
    
    def matrix_mul(A, B, mod):
        # Multiply two matrices modulo `mod`
        return [[sum((A[i][k] * B[k][j]) % mod for k in range(len(B))) % mod for j in range(len(B[0]))] for i in range(len(A))]
    
    def gaussian_elimination(A, mod):
        # Perform Gaussian elimination on matrix A modulo `mod`
        n = len(A)
        for i in range(n):
            max_row = i
            for k in range(i + 1, n):
                if abs(A[k][i]) > abs(A[max_row][i]):
                    max_row = k
            A[i], A[max_row] = A[max_row], A[i]
            pivot = A[i][i]
            if pivot == 0:
                continue
            for j in range(i, n):
                A[i][j] = (A[i][j] * pow(pivot, -1, mod)) % mod
            for k in range(n):
                if k != i:
                    factor = A[k][i]
                    for j in range(i, n):
                        A[k][j] = (A[k][j] - factor * A[i][j]) % mod
        return A
    
    def rank(A, mod):
        # Compute the rank of matrix A modulo `mod`
        A_rref = gaussian_elimination(A, mod)
        rank = 0
        for row in A_rref:
            if any(row):
                rank += 1
        return rank
    
    def ideal_rank_variance(instance, mod):
        # Compute the rank variance of the ideal generated by the instance modulo `mod`
        A, B = instance
        I = matrix_sub(matrix_mul(A, A, mod), matrix_mul(B, B, mod))
        R = rank(I, mod)
        return R
    
    def minimal_local_ring_rank(instance, mod):
        # Compute the minimal local ring rank of the ideal generated by the instance modulo `mod`
        A, B = instance
        I = matrix_sub(matrix_mul(A, A, mod), matrix_mul(B, B, mod))
        R = rank(I, mod)
        return R
    
    def alpha(V):
        # Define the constant α (this is a placeholder; replace with actual value if known)
        return 1.0
    
    n_values = [5, 10, 15, 20, 30, 40]
    results = []
    
    for n in n_values:
        instance = generate_random_communication_instance(n)
        V = ideal_rank_variance(instance, mod=2)
        R = minimal_local_ring_rank(instance, mod=2)
        results.append({
            "n": n,
            "V": V,
            "R": R
        })
    
    mean_V = sum(result["V"] for result in results) / len(results)
    mean_R = sum(result["R"] for result in results) / len(results)
    max_n = max(result["n"] for result in results)
    
    conjecture_holds = all(R <= alpha(V)**2 for R, V in zip([result["R"] for result in results], [result["V"] for result in results]))
    
    counterexample = "" if conjecture_holds else "mapping_undefined"
    
    return {
        "metric_name": "minimal_local_ring_rank_bound",
        "metric_value": mean_R,
        "instances_tested": len(results),
        "n_max": max_n,
        "conjecture_holds": conjecture_holds,
        "counterexample": counterexample
    }

if __name__ == "__main__":
    seeds = [int(s) for s in sys.argv[1:]] if sys.argv[1:] else [2, 3, 5, 7, 11, 13, 17, 19, 23, 29] * 3
    results = []
    
    for seed in seeds:
        trial_result = run_trial(seed)
        print(f"TRIAL: {trial_result}")
        results.append(trial_result)
    
    mean_value = sum(result["metric_value"] for result in results) / len(results)
    std_value = math.sqrt(sum((result["metric_value"] - mean_value)**2 for result in results) / len(results))
    support_fraction = sum(1 for result in results if result["conjecture_holds"]) / len(results)
    
    if all(result["conjecture_holds"] for result in results):
        print(f"RESULT: SUPPORTED mean={mean_value} std={std_value} support_fraction={support_fraction}")
    elif any(not result["conjecture_holds"] for result in results):
        first_failing_seed = next(seed for seed, result in zip(seeds, results) if not result["conjecture_holds"])
        print(f"RESULT: FALSIFIED counterexample=\"mapping_undefined\" first_failing_seed={first_failing_seed}")
    else:
        print("RESULT: INCONCLUSIVE reason=unreachable")